// Generated by gencpp from file rm_msgs/BulletAllowance.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_BULLETALLOWANCE_H
#define RM_MSGS_MESSAGE_BULLETALLOWANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct BulletAllowance_
{
  typedef BulletAllowance_<ContainerAllocator> Type;

  BulletAllowance_()
    : bullet_allowance_num_17_mm(0)
    , bullet_allowance_num_42_mm(0)
    , coin_remaining_num(0)
    , projectile_allowance_fortress(0)
    , stamp()  {
    }
  BulletAllowance_(const ContainerAllocator& _alloc)
    : bullet_allowance_num_17_mm(0)
    , bullet_allowance_num_42_mm(0)
    , coin_remaining_num(0)
    , projectile_allowance_fortress(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint16_t _bullet_allowance_num_17_mm_type;
  _bullet_allowance_num_17_mm_type bullet_allowance_num_17_mm;

   typedef uint16_t _bullet_allowance_num_42_mm_type;
  _bullet_allowance_num_42_mm_type bullet_allowance_num_42_mm;

   typedef uint16_t _coin_remaining_num_type;
  _coin_remaining_num_type coin_remaining_num;

   typedef uint16_t _projectile_allowance_fortress_type;
  _projectile_allowance_fortress_type projectile_allowance_fortress;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::BulletAllowance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::BulletAllowance_<ContainerAllocator> const> ConstPtr;

}; // struct BulletAllowance_

typedef ::rm_msgs::BulletAllowance_<std::allocator<void> > BulletAllowance;

typedef boost::shared_ptr< ::rm_msgs::BulletAllowance > BulletAllowancePtr;
typedef boost::shared_ptr< ::rm_msgs::BulletAllowance const> BulletAllowanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::BulletAllowance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::BulletAllowance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::BulletAllowance_<ContainerAllocator1> & lhs, const ::rm_msgs::BulletAllowance_<ContainerAllocator2> & rhs)
{
  return lhs.bullet_allowance_num_17_mm == rhs.bullet_allowance_num_17_mm &&
    lhs.bullet_allowance_num_42_mm == rhs.bullet_allowance_num_42_mm &&
    lhs.coin_remaining_num == rhs.coin_remaining_num &&
    lhs.projectile_allowance_fortress == rhs.projectile_allowance_fortress &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::BulletAllowance_<ContainerAllocator1> & lhs, const ::rm_msgs::BulletAllowance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::BulletAllowance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::BulletAllowance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::BulletAllowance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d37e99d879c3fd6d3eb6ff551cb04737";
  }

  static const char* value(const ::rm_msgs::BulletAllowance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd37e99d879c3fd6dULL;
  static const uint64_t static_value2 = 0x3eb6ff551cb04737ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/BulletAllowance";
  }

  static const char* value(const ::rm_msgs::BulletAllowance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 bullet_allowance_num_17_mm\n"
"uint16 bullet_allowance_num_42_mm\n"
"uint16 coin_remaining_num\n"
"uint16 projectile_allowance_fortress\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::BulletAllowance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bullet_allowance_num_17_mm);
      stream.next(m.bullet_allowance_num_42_mm);
      stream.next(m.coin_remaining_num);
      stream.next(m.projectile_allowance_fortress);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BulletAllowance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::BulletAllowance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::BulletAllowance_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "bullet_allowance_num_17_mm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.bullet_allowance_num_17_mm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bullet_allowance_num_42_mm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.bullet_allowance_num_42_mm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "coin_remaining_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.coin_remaining_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "projectile_allowance_fortress: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.projectile_allowance_fortress);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_BULLETALLOWANCE_H
