// Generated by gencpp from file rm_msgs/Dart.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_DART_H
#define RM_MSGS_MESSAGE_DART_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Dart_
{
  typedef Dart_<ContainerAllocator> Type;

  Dart_()
    : distance(0)
    , height(0)
    , is_found(false)
    , stamp()  {
    }
  Dart_(const ContainerAllocator& _alloc)
    : distance(0)
    , height(0)
    , is_found(false)
    , stamp()  {
  (void)_alloc;
    }



   typedef int16_t _distance_type;
  _distance_type distance;

   typedef int16_t _height_type;
  _height_type height;

   typedef uint8_t _is_found_type;
  _is_found_type is_found;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::Dart_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Dart_<ContainerAllocator> const> ConstPtr;

}; // struct Dart_

typedef ::rm_msgs::Dart_<std::allocator<void> > Dart;

typedef boost::shared_ptr< ::rm_msgs::Dart > DartPtr;
typedef boost::shared_ptr< ::rm_msgs::Dart const> DartConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Dart_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Dart_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Dart_<ContainerAllocator1> & lhs, const ::rm_msgs::Dart_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance &&
    lhs.height == rhs.height &&
    lhs.is_found == rhs.is_found &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Dart_<ContainerAllocator1> & lhs, const ::rm_msgs::Dart_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Dart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Dart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Dart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Dart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Dart_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Dart_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Dart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a786858289d996b001b391aeda1dc1a4";
  }

  static const char* value(const ::rm_msgs::Dart_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa786858289d996b0ULL;
  static const uint64_t static_value2 = 0x01b391aeda1dc1a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Dart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Dart";
  }

  static const char* value(const ::rm_msgs::Dart_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Dart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 distance\n"
"int16 height\n"
"bool is_found\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::Dart_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Dart_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.height);
      stream.next(m.is_found);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dart_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Dart_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Dart_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<int16_t>::stream(s, indent + "  ", v.distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<int16_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_found);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_DART_H
