// Generated by gencpp from file rm_msgs/DartClientCmd.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_DARTCLIENTCMD_H
#define RM_MSGS_MESSAGE_DARTCLIENTCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct DartClientCmd_
{
  typedef DartClientCmd_<ContainerAllocator> Type;

  DartClientCmd_()
    : dart_launch_opening_status(0)
    , target_change_time(0)
    , latest_launch_cmd_time(0)
    , stamp()  {
    }
  DartClientCmd_(const ContainerAllocator& _alloc)
    : dart_launch_opening_status(0)
    , target_change_time(0)
    , latest_launch_cmd_time(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _dart_launch_opening_status_type;
  _dart_launch_opening_status_type dart_launch_opening_status;

   typedef uint16_t _target_change_time_type;
  _target_change_time_type target_change_time;

   typedef uint16_t _latest_launch_cmd_time_type;
  _latest_launch_cmd_time_type latest_launch_cmd_time;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CLOSED)
  #undef CLOSED
#endif
#if defined(_WIN32) && defined(OPENING_OR_CLOSING)
  #undef OPENING_OR_CLOSING
#endif
#if defined(_WIN32) && defined(OPENED)
  #undef OPENED
#endif

  enum {
    CLOSED = 1u,
    OPENING_OR_CLOSING = 2u,
    OPENED = 0u,
  };


  typedef boost::shared_ptr< ::rm_msgs::DartClientCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::DartClientCmd_<ContainerAllocator> const> ConstPtr;

}; // struct DartClientCmd_

typedef ::rm_msgs::DartClientCmd_<std::allocator<void> > DartClientCmd;

typedef boost::shared_ptr< ::rm_msgs::DartClientCmd > DartClientCmdPtr;
typedef boost::shared_ptr< ::rm_msgs::DartClientCmd const> DartClientCmdConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::DartClientCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::DartClientCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::DartClientCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::DartClientCmd_<ContainerAllocator2> & rhs)
{
  return lhs.dart_launch_opening_status == rhs.dart_launch_opening_status &&
    lhs.target_change_time == rhs.target_change_time &&
    lhs.latest_launch_cmd_time == rhs.latest_launch_cmd_time &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::DartClientCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::DartClientCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::DartClientCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::DartClientCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::DartClientCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35bb2f324581a84628fc6e104a35144c";
  }

  static const char* value(const ::rm_msgs::DartClientCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35bb2f324581a846ULL;
  static const uint64_t static_value2 = 0x28fc6e104a35144cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/DartClientCmd";
  }

  static const char* value(const ::rm_msgs::DartClientCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 dart_launch_opening_status\n"
"uint16 target_change_time\n"
"uint16 latest_launch_cmd_time\n"
"\n"
"uint8 CLOSED = 1\n"
"uint8 OPENING_OR_CLOSING = 2\n"
"uint8 OPENED = 0\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::DartClientCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dart_launch_opening_status);
      stream.next(m.target_change_time);
      stream.next(m.latest_launch_cmd_time);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DartClientCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::DartClientCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::DartClientCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "dart_launch_opening_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dart_launch_opening_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_change_time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_change_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latest_launch_cmd_time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.latest_launch_cmd_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_DARTCLIENTCMD_H
