// Generated by gencpp from file rm_msgs/ExchangerMsg.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_EXCHANGERMSG_H
#define RM_MSGS_MESSAGE_EXCHANGERMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Pose.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct ExchangerMsg_
{
  typedef ExchangerMsg_<ContainerAllocator> Type;

  ExchangerMsg_()
    : flag(0)
    , shape(0)
    , middle_point()
    , pose()  {
    }
  ExchangerMsg_(const ContainerAllocator& _alloc)
    : flag(0)
    , shape(0)
    , middle_point(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef uint8_t _shape_type;
  _shape_type shape;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _middle_point_type;
  _middle_point_type middle_point;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::rm_msgs::ExchangerMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ExchangerMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ExchangerMsg_

typedef ::rm_msgs::ExchangerMsg_<std::allocator<void> > ExchangerMsg;

typedef boost::shared_ptr< ::rm_msgs::ExchangerMsg > ExchangerMsgPtr;
typedef boost::shared_ptr< ::rm_msgs::ExchangerMsg const> ExchangerMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ExchangerMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ExchangerMsg_<ContainerAllocator1> & lhs, const ::rm_msgs::ExchangerMsg_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag &&
    lhs.shape == rhs.shape &&
    lhs.middle_point == rhs.middle_point &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ExchangerMsg_<ContainerAllocator1> & lhs, const ::rm_msgs::ExchangerMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ExchangerMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ExchangerMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ExchangerMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6d3cfca8ef03650140ca2d366044574";
  }

  static const char* value(const ::rm_msgs::ExchangerMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6d3cfca8ef03650ULL;
  static const uint64_t static_value2 = 0x140ca2d366044574ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ExchangerMsg";
  }

  static const char* value(const ::rm_msgs::ExchangerMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 flag\n"
"uint8 shape\n"
"geometry_msgs/Point middle_point\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rm_msgs::ExchangerMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.shape);
      stream.next(m.middle_point);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExchangerMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ExchangerMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ExchangerMsg_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "shape: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shape);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "middle_point: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.middle_point);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_EXCHANGERMSG_H
