// Generated by gencpp from file rm_msgs/PriorityArray.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_PRIORITYARRAY_H
#define RM_MSGS_MESSAGE_PRIORITYARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct PriorityArray_
{
  typedef PriorityArray_<ContainerAllocator> Type;

  PriorityArray_()
    : rank_arr()  {
    }
  PriorityArray_(const ContainerAllocator& _alloc)
    : rank_arr(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _rank_arr_type;
  _rank_arr_type rank_arr;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(HERO)
  #undef HERO
#endif
#if defined(_WIN32) && defined(ENGINEER)
  #undef ENGINEER
#endif
#if defined(_WIN32) && defined(INFANTRY3)
  #undef INFANTRY3
#endif
#if defined(_WIN32) && defined(INFANTRY4)
  #undef INFANTRY4
#endif
#if defined(_WIN32) && defined(INFANTRY5)
  #undef INFANTRY5
#endif
#if defined(_WIN32) && defined(OUTPOST)
  #undef OUTPOST
#endif
#if defined(_WIN32) && defined(SENTRY)
  #undef SENTRY
#endif
#if defined(_WIN32) && defined(BASE)
  #undef BASE
#endif

  enum {
    HERO = 0u,
    ENGINEER = 1u,
    INFANTRY3 = 2u,
    INFANTRY4 = 3u,
    INFANTRY5 = 4u,
    OUTPOST = 5u,
    SENTRY = 6u,
    BASE = 7u,
  };


  typedef boost::shared_ptr< ::rm_msgs::PriorityArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::PriorityArray_<ContainerAllocator> const> ConstPtr;

}; // struct PriorityArray_

typedef ::rm_msgs::PriorityArray_<std::allocator<void> > PriorityArray;

typedef boost::shared_ptr< ::rm_msgs::PriorityArray > PriorityArrayPtr;
typedef boost::shared_ptr< ::rm_msgs::PriorityArray const> PriorityArrayConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::PriorityArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::PriorityArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::PriorityArray_<ContainerAllocator1> & lhs, const ::rm_msgs::PriorityArray_<ContainerAllocator2> & rhs)
{
  return lhs.rank_arr == rhs.rank_arr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::PriorityArray_<ContainerAllocator1> & lhs, const ::rm_msgs::PriorityArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PriorityArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PriorityArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PriorityArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PriorityArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PriorityArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PriorityArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::PriorityArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eb29adee789c861a1d9aa2167b08593";
  }

  static const char* value(const ::rm_msgs::PriorityArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eb29adee789c861ULL;
  static const uint64_t static_value2 = 0xa1d9aa2167b08593ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::PriorityArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/PriorityArray";
  }

  static const char* value(const ::rm_msgs::PriorityArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::PriorityArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 HERO = 0\n"
"uint8 ENGINEER = 1\n"
"uint8 INFANTRY3 = 2\n"
"uint8 INFANTRY4 = 3\n"
"uint8 INFANTRY5 = 4\n"
"uint8 OUTPOST = 5\n"
"uint8 SENTRY = 6\n"
"uint8 BASE = 7\n"
"\n"
"uint8[] rank_arr\n"
;
  }

  static const char* value(const ::rm_msgs::PriorityArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::PriorityArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rank_arr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PriorityArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::PriorityArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::PriorityArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "rank_arr: ";
    if (v.rank_arr.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.rank_arr.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.rank_arr[i]);
    }
    if (v.rank_arr.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_PRIORITYARRAY_H
