// Generated by gencpp from file rm_msgs/RadarInfo.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARINFO_H
#define RM_MSGS_MESSAGE_RADARINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarInfo_
{
  typedef RadarInfo_<ContainerAllocator> Type;

  RadarInfo_()
    : radar_info(0)  {
    }
  RadarInfo_(const ContainerAllocator& _alloc)
    : radar_info(0)  {
  (void)_alloc;
    }



   typedef uint8_t _radar_info_type;
  _radar_info_type radar_info;





  typedef boost::shared_ptr< ::rm_msgs::RadarInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RadarInfo_

typedef ::rm_msgs::RadarInfo_<std::allocator<void> > RadarInfo;

typedef boost::shared_ptr< ::rm_msgs::RadarInfo > RadarInfoPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarInfo const> RadarInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarInfo_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarInfo_<ContainerAllocator2> & rhs)
{
  return lhs.radar_info == rhs.radar_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarInfo_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e33b2c279afbab996e05f5134608f519";
  }

  static const char* value(const ::rm_msgs::RadarInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe33b2c279afbab99ULL;
  static const uint64_t static_value2 = 0x6e05f5134608f519ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarInfo";
  }

  static const char* value(const ::rm_msgs::RadarInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 radar_info\n"
;
  }

  static const char* value(const ::rm_msgs::RadarInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radar_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "radar_info: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radar_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARINFO_H
