// Generated by gencpp from file rm_msgs/VisualizeStateData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_VISUALIZESTATEDATA_H
#define RM_MSGS_MESSAGE_VISUALIZESTATEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct VisualizeStateData_
{
  typedef VisualizeStateData_<ContainerAllocator> Type;

  VisualizeStateData_()
    : state()  {
    }
  VisualizeStateData_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::rm_msgs::VisualizeStateData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::VisualizeStateData_<ContainerAllocator> const> ConstPtr;

}; // struct VisualizeStateData_

typedef ::rm_msgs::VisualizeStateData_<std::allocator<void> > VisualizeStateData;

typedef boost::shared_ptr< ::rm_msgs::VisualizeStateData > VisualizeStateDataPtr;
typedef boost::shared_ptr< ::rm_msgs::VisualizeStateData const> VisualizeStateDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::VisualizeStateData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::VisualizeStateData_<ContainerAllocator1> & lhs, const ::rm_msgs::VisualizeStateData_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::VisualizeStateData_<ContainerAllocator1> & lhs, const ::rm_msgs::VisualizeStateData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::VisualizeStateData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::VisualizeStateData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::VisualizeStateData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5958fa30c9a253a1f2857ed1c1f2b7f";
  }

  static const char* value(const ::rm_msgs::VisualizeStateData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5958fa30c9a253aULL;
  static const uint64_t static_value2 = 0x1f2857ed1c1f2b7fULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/VisualizeStateData";
  }

  static const char* value(const ::rm_msgs::VisualizeStateData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] state\n"
;
  }

  static const char* value(const ::rm_msgs::VisualizeStateData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualizeStateData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::VisualizeStateData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::VisualizeStateData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    if (v.state.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.state[i]);
    }
    if (v.state.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_VISUALIZESTATEDATA_H
