# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/ClientMapReceiveData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ClientMapReceiveData(genpy.Message):
  _md5sum = "765860ed57371d5f547d7681e64c9b02"
  _type = "rm_msgs/ClientMapReceiveData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 hero_position_x
uint16 hero_position_y
uint16 engineer_position_x
uint16 engineer_position_y
uint16 infantry_3_position_x
uint16 infantry_3_position_y
uint16 infantry_4_position_x
uint16 infantry_4_position_y
uint16 infantry_5_position_x
uint16 infantry_5_position_y
uint16 sentry_position_x
uint16 sentry_position_y

time stamp
"""
  __slots__ = ['hero_position_x','hero_position_y','engineer_position_x','engineer_position_y','infantry_3_position_x','infantry_3_position_y','infantry_4_position_x','infantry_4_position_y','infantry_5_position_x','infantry_5_position_y','sentry_position_x','sentry_position_y','stamp']
  _slot_types = ['uint16','uint16','uint16','uint16','uint16','uint16','uint16','uint16','uint16','uint16','uint16','uint16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hero_position_x,hero_position_y,engineer_position_x,engineer_position_y,infantry_3_position_x,infantry_3_position_y,infantry_4_position_x,infantry_4_position_y,infantry_5_position_x,infantry_5_position_y,sentry_position_x,sentry_position_y,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ClientMapReceiveData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hero_position_x is None:
        self.hero_position_x = 0
      if self.hero_position_y is None:
        self.hero_position_y = 0
      if self.engineer_position_x is None:
        self.engineer_position_x = 0
      if self.engineer_position_y is None:
        self.engineer_position_y = 0
      if self.infantry_3_position_x is None:
        self.infantry_3_position_x = 0
      if self.infantry_3_position_y is None:
        self.infantry_3_position_y = 0
      if self.infantry_4_position_x is None:
        self.infantry_4_position_x = 0
      if self.infantry_4_position_y is None:
        self.infantry_4_position_y = 0
      if self.infantry_5_position_x is None:
        self.infantry_5_position_x = 0
      if self.infantry_5_position_y is None:
        self.infantry_5_position_y = 0
      if self.sentry_position_x is None:
        self.sentry_position_x = 0
      if self.sentry_position_y is None:
        self.sentry_position_y = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.hero_position_x = 0
      self.hero_position_y = 0
      self.engineer_position_x = 0
      self.engineer_position_y = 0
      self.infantry_3_position_x = 0
      self.infantry_3_position_y = 0
      self.infantry_4_position_x = 0
      self.infantry_4_position_y = 0
      self.infantry_5_position_x = 0
      self.infantry_5_position_y = 0
      self.sentry_position_x = 0
      self.sentry_position_y = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12H2I().pack(_x.hero_position_x, _x.hero_position_y, _x.engineer_position_x, _x.engineer_position_y, _x.infantry_3_position_x, _x.infantry_3_position_y, _x.infantry_4_position_x, _x.infantry_4_position_y, _x.infantry_5_position_x, _x.infantry_5_position_y, _x.sentry_position_x, _x.sentry_position_y, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.hero_position_x, _x.hero_position_y, _x.engineer_position_x, _x.engineer_position_y, _x.infantry_3_position_x, _x.infantry_3_position_y, _x.infantry_4_position_x, _x.infantry_4_position_y, _x.infantry_5_position_x, _x.infantry_5_position_y, _x.sentry_position_x, _x.sentry_position_y, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_12H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12H2I().pack(_x.hero_position_x, _x.hero_position_y, _x.engineer_position_x, _x.engineer_position_y, _x.infantry_3_position_x, _x.infantry_3_position_y, _x.infantry_4_position_x, _x.infantry_4_position_y, _x.infantry_5_position_x, _x.infantry_5_position_y, _x.sentry_position_x, _x.sentry_position_y, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.hero_position_x, _x.hero_position_y, _x.engineer_position_x, _x.engineer_position_y, _x.infantry_3_position_x, _x.infantry_3_position_y, _x.infantry_4_position_x, _x.infantry_4_position_y, _x.infantry_5_position_x, _x.infantry_5_position_y, _x.sentry_position_x, _x.sentry_position_y, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_12H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12H2I = None
def _get_struct_12H2I():
    global _struct_12H2I
    if _struct_12H2I is None:
        _struct_12H2I = struct.Struct("<12H2I")
    return _struct_12H2I
