# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/ClientMapSendData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ClientMapSendData(genpy.Message):
  _md5sum = "aee27039134a834173f127a33eff61f7"
  _type = "rm_msgs/ClientMapSendData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 KEY_Q = 81
uint8 KEY_W = 87
uint8 KEY_E = 69
uint8 KEY_R = 82
uint8 KEY_T = 84
uint8 KEY_Y = 89
uint8 KEY_U = 85
uint8 KEY_O = 79

uint8 KEY_A = 65
uint8 KEY_S = 83
uint8 KEY_D = 68
uint8 KEY_F = 70
uint8 KEY_G = 71
uint8 KEY_H = 72
uint8 KEY_J = 74
uint8 KEY_K = 75
uint8 KEY_L = 76

uint8 KEY_Z = 90
uint8 KEY_X = 88
uint8 KEY_C = 67
uint8 KEY_V = 86
uint8 KEY_N = 78

float32 target_position_x
float32 target_position_y
uint8 command_keyboard
uint8 target_robot_ID
uint8 cmd_source
"""
  # Pseudo-constants
  KEY_Q = 81
  KEY_W = 87
  KEY_E = 69
  KEY_R = 82
  KEY_T = 84
  KEY_Y = 89
  KEY_U = 85
  KEY_O = 79
  KEY_A = 65
  KEY_S = 83
  KEY_D = 68
  KEY_F = 70
  KEY_G = 71
  KEY_H = 72
  KEY_J = 74
  KEY_K = 75
  KEY_L = 76
  KEY_Z = 90
  KEY_X = 88
  KEY_C = 67
  KEY_V = 86
  KEY_N = 78

  __slots__ = ['target_position_x','target_position_y','command_keyboard','target_robot_ID','cmd_source']
  _slot_types = ['float32','float32','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target_position_x,target_position_y,command_keyboard,target_robot_ID,cmd_source

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ClientMapSendData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.target_position_x is None:
        self.target_position_x = 0.
      if self.target_position_y is None:
        self.target_position_y = 0.
      if self.command_keyboard is None:
        self.command_keyboard = 0
      if self.target_robot_ID is None:
        self.target_robot_ID = 0
      if self.cmd_source is None:
        self.cmd_source = 0
    else:
      self.target_position_x = 0.
      self.target_position_y = 0.
      self.command_keyboard = 0
      self.target_robot_ID = 0
      self.cmd_source = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f3B().pack(_x.target_position_x, _x.target_position_y, _x.command_keyboard, _x.target_robot_ID, _x.cmd_source))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.target_position_x, _x.target_position_y, _x.command_keyboard, _x.target_robot_ID, _x.cmd_source,) = _get_struct_2f3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f3B().pack(_x.target_position_x, _x.target_position_y, _x.command_keyboard, _x.target_robot_ID, _x.cmd_source))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.target_position_x, _x.target_position_y, _x.command_keyboard, _x.target_robot_ID, _x.cmd_source,) = _get_struct_2f3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f3B = None
def _get_struct_2f3B():
    global _struct_2f3B
    if _struct_2f3B is None:
        _struct_2f3B = struct.Struct("<2f3B")
    return _struct_2f3B
