# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/DartClientCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class DartClientCmd(genpy.Message):
  _md5sum = "35bb2f324581a84628fc6e104a35144c"
  _type = "rm_msgs/DartClientCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 dart_launch_opening_status
uint16 target_change_time
uint16 latest_launch_cmd_time

uint8 CLOSED = 1
uint8 OPENING_OR_CLOSING = 2
uint8 OPENED = 0

time stamp
"""
  # Pseudo-constants
  CLOSED = 1
  OPENING_OR_CLOSING = 2
  OPENED = 0

  __slots__ = ['dart_launch_opening_status','target_change_time','latest_launch_cmd_time','stamp']
  _slot_types = ['uint8','uint16','uint16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dart_launch_opening_status,target_change_time,latest_launch_cmd_time,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DartClientCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.dart_launch_opening_status is None:
        self.dart_launch_opening_status = 0
      if self.target_change_time is None:
        self.target_change_time = 0
      if self.latest_launch_cmd_time is None:
        self.latest_launch_cmd_time = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.dart_launch_opening_status = 0
      self.target_change_time = 0
      self.latest_launch_cmd_time = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2H2I().pack(_x.dart_launch_opening_status, _x.target_change_time, _x.latest_launch_cmd_time, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.dart_launch_opening_status, _x.target_change_time, _x.latest_launch_cmd_time, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_B2H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2H2I().pack(_x.dart_launch_opening_status, _x.target_change_time, _x.latest_launch_cmd_time, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.dart_launch_opening_status, _x.target_change_time, _x.latest_launch_cmd_time, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_B2H2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2H2I = None
def _get_struct_B2H2I():
    global _struct_B2H2I
    if _struct_B2H2I is None:
        _struct_B2H2I = struct.Struct("<B2H2I")
    return _struct_B2H2I
