# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/EventData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class EventData(genpy.Message):
  _md5sum = "0e0fe7f33f8d70cbb516e24d1e30721c"
  _type = "rm_msgs/EventData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool overlapping_supply_station_state
bool nan_overlapping_supply_station_state
bool supplier_zone_state
bool small_power_rune_state
bool large_power_rune_state
uint8 central_elevated_ground_state
uint8 trapezoidal_elevated_ground_state
uint16 be_hit_time
uint8 be_hit_target
uint8 central_point_state
uint8 own_fortress_state

time stamp
"""
  __slots__ = ['overlapping_supply_station_state','nan_overlapping_supply_station_state','supplier_zone_state','small_power_rune_state','large_power_rune_state','central_elevated_ground_state','trapezoidal_elevated_ground_state','be_hit_time','be_hit_target','central_point_state','own_fortress_state','stamp']
  _slot_types = ['bool','bool','bool','bool','bool','uint8','uint8','uint16','uint8','uint8','uint8','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       overlapping_supply_station_state,nan_overlapping_supply_station_state,supplier_zone_state,small_power_rune_state,large_power_rune_state,central_elevated_ground_state,trapezoidal_elevated_ground_state,be_hit_time,be_hit_target,central_point_state,own_fortress_state,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EventData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.overlapping_supply_station_state is None:
        self.overlapping_supply_station_state = False
      if self.nan_overlapping_supply_station_state is None:
        self.nan_overlapping_supply_station_state = False
      if self.supplier_zone_state is None:
        self.supplier_zone_state = False
      if self.small_power_rune_state is None:
        self.small_power_rune_state = False
      if self.large_power_rune_state is None:
        self.large_power_rune_state = False
      if self.central_elevated_ground_state is None:
        self.central_elevated_ground_state = 0
      if self.trapezoidal_elevated_ground_state is None:
        self.trapezoidal_elevated_ground_state = 0
      if self.be_hit_time is None:
        self.be_hit_time = 0
      if self.be_hit_target is None:
        self.be_hit_target = 0
      if self.central_point_state is None:
        self.central_point_state = 0
      if self.own_fortress_state is None:
        self.own_fortress_state = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.overlapping_supply_station_state = False
      self.nan_overlapping_supply_station_state = False
      self.supplier_zone_state = False
      self.small_power_rune_state = False
      self.large_power_rune_state = False
      self.central_elevated_ground_state = 0
      self.trapezoidal_elevated_ground_state = 0
      self.be_hit_time = 0
      self.be_hit_target = 0
      self.central_point_state = 0
      self.own_fortress_state = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7BH3B2I().pack(_x.overlapping_supply_station_state, _x.nan_overlapping_supply_station_state, _x.supplier_zone_state, _x.small_power_rune_state, _x.large_power_rune_state, _x.central_elevated_ground_state, _x.trapezoidal_elevated_ground_state, _x.be_hit_time, _x.be_hit_target, _x.central_point_state, _x.own_fortress_state, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.overlapping_supply_station_state, _x.nan_overlapping_supply_station_state, _x.supplier_zone_state, _x.small_power_rune_state, _x.large_power_rune_state, _x.central_elevated_ground_state, _x.trapezoidal_elevated_ground_state, _x.be_hit_time, _x.be_hit_target, _x.central_point_state, _x.own_fortress_state, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_7BH3B2I().unpack(str[start:end])
      self.overlapping_supply_station_state = bool(self.overlapping_supply_station_state)
      self.nan_overlapping_supply_station_state = bool(self.nan_overlapping_supply_station_state)
      self.supplier_zone_state = bool(self.supplier_zone_state)
      self.small_power_rune_state = bool(self.small_power_rune_state)
      self.large_power_rune_state = bool(self.large_power_rune_state)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7BH3B2I().pack(_x.overlapping_supply_station_state, _x.nan_overlapping_supply_station_state, _x.supplier_zone_state, _x.small_power_rune_state, _x.large_power_rune_state, _x.central_elevated_ground_state, _x.trapezoidal_elevated_ground_state, _x.be_hit_time, _x.be_hit_target, _x.central_point_state, _x.own_fortress_state, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.overlapping_supply_station_state, _x.nan_overlapping_supply_station_state, _x.supplier_zone_state, _x.small_power_rune_state, _x.large_power_rune_state, _x.central_elevated_ground_state, _x.trapezoidal_elevated_ground_state, _x.be_hit_time, _x.be_hit_target, _x.central_point_state, _x.own_fortress_state, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_7BH3B2I().unpack(str[start:end])
      self.overlapping_supply_station_state = bool(self.overlapping_supply_station_state)
      self.nan_overlapping_supply_station_state = bool(self.nan_overlapping_supply_station_state)
      self.supplier_zone_state = bool(self.supplier_zone_state)
      self.small_power_rune_state = bool(self.small_power_rune_state)
      self.large_power_rune_state = bool(self.large_power_rune_state)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7BH3B2I = None
def _get_struct_7BH3B2I():
    global _struct_7BH3B2I
    if _struct_7BH3B2I is None:
        _struct_7BH3B2I = struct.Struct("<7BH3B2I")
    return _struct_7BH3B2I
