# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/LocalHeatState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class LocalHeatState(genpy.Message):
  _md5sum = "29a8a14a26935854a78d9ab8fc58289b"
  _type = "rm_msgs/LocalHeatState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 friction_speed
float64 friction_change_speed
float64 friction_change_speed_derivative
bool has_shoot
time stamp
"""
  __slots__ = ['friction_speed','friction_change_speed','friction_change_speed_derivative','has_shoot','stamp']
  _slot_types = ['float64','float64','float64','bool','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       friction_speed,friction_change_speed,friction_change_speed_derivative,has_shoot,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocalHeatState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.friction_speed is None:
        self.friction_speed = 0.
      if self.friction_change_speed is None:
        self.friction_change_speed = 0.
      if self.friction_change_speed_derivative is None:
        self.friction_change_speed_derivative = 0.
      if self.has_shoot is None:
        self.has_shoot = False
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.friction_speed = 0.
      self.friction_change_speed = 0.
      self.friction_change_speed_derivative = 0.
      self.has_shoot = False
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3dB2I().pack(_x.friction_speed, _x.friction_change_speed, _x.friction_change_speed_derivative, _x.has_shoot, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.friction_speed, _x.friction_change_speed, _x.friction_change_speed_derivative, _x.has_shoot, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3dB2I().unpack(str[start:end])
      self.has_shoot = bool(self.has_shoot)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3dB2I().pack(_x.friction_speed, _x.friction_change_speed, _x.friction_change_speed_derivative, _x.has_shoot, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.friction_speed, _x.friction_change_speed, _x.friction_change_speed_derivative, _x.has_shoot, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3dB2I().unpack(str[start:end])
      self.has_shoot = bool(self.has_shoot)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3dB2I = None
def _get_struct_3dB2I():
    global _struct_3dB2I
    if _struct_3dB2I is None:
        _struct_3dB2I = struct.Struct("<3dB2I")
    return _struct_3dB2I
