# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarToSentry.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RadarToSentry(genpy.Message):
  _md5sum = "55598f76d4bb77ccd6286fc50e5b4aed"
  _type = "rm_msgs/RadarToSentry"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 robot_ID
float32 position_x
float32 position_y
bool engineer_marked
"""
  __slots__ = ['robot_ID','position_x','position_y','engineer_marked']
  _slot_types = ['uint8','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robot_ID,position_x,position_y,engineer_marked

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarToSentry, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robot_ID is None:
        self.robot_ID = 0
      if self.position_x is None:
        self.position_x = 0.
      if self.position_y is None:
        self.position_y = 0.
      if self.engineer_marked is None:
        self.engineer_marked = False
    else:
      self.robot_ID = 0
      self.position_x = 0.
      self.position_y = 0.
      self.engineer_marked = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2fB().pack(_x.robot_ID, _x.position_x, _x.position_y, _x.engineer_marked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.robot_ID, _x.position_x, _x.position_y, _x.engineer_marked,) = _get_struct_B2fB().unpack(str[start:end])
      self.engineer_marked = bool(self.engineer_marked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2fB().pack(_x.robot_ID, _x.position_x, _x.position_y, _x.engineer_marked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.robot_ID, _x.position_x, _x.position_y, _x.engineer_marked,) = _get_struct_B2fB().unpack(str[start:end])
      self.engineer_marked = bool(self.engineer_marked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2fB = None
def _get_struct_B2fB():
    global _struct_B2fB
    if _struct_B2fB is None:
        _struct_B2fB = struct.Struct("<B2fB")
    return _struct_B2fB
