# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/SentryInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SentryInfo(genpy.Message):
  _md5sum = "12d17492af26f6bdf5a621bccb488999"
  _type = "rm_msgs/SentryInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 sentry_info
bool is_out_of_war
uint16 remaining_bullets_can_supply
"""
  __slots__ = ['sentry_info','is_out_of_war','remaining_bullets_can_supply']
  _slot_types = ['uint32','bool','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sentry_info,is_out_of_war,remaining_bullets_can_supply

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SentryInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sentry_info is None:
        self.sentry_info = 0
      if self.is_out_of_war is None:
        self.is_out_of_war = False
      if self.remaining_bullets_can_supply is None:
        self.remaining_bullets_can_supply = 0
    else:
      self.sentry_info = 0
      self.is_out_of_war = False
      self.remaining_bullets_can_supply = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IBH().pack(_x.sentry_info, _x.is_out_of_war, _x.remaining_bullets_can_supply))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.sentry_info, _x.is_out_of_war, _x.remaining_bullets_can_supply,) = _get_struct_IBH().unpack(str[start:end])
      self.is_out_of_war = bool(self.is_out_of_war)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IBH().pack(_x.sentry_info, _x.is_out_of_war, _x.remaining_bullets_can_supply))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.sentry_info, _x.is_out_of_war, _x.remaining_bullets_can_supply,) = _get_struct_IBH().unpack(str[start:end])
      self.is_out_of_war = bool(self.is_out_of_war)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IBH = None
def _get_struct_IBH():
    global _struct_IBH
    if _struct_IBH is None:
        _struct_IBH = struct.Struct("<IBH")
    return _struct_IBH
