// Generated by gencpp from file rm_msgs/Buff.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_BUFF_H
#define RM_MSGS_MESSAGE_BUFF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Buff_
{
  typedef Buff_<ContainerAllocator> Type;

  Buff_()
    : recovery_buff(0)
    , cooling_buff(0)
    , defence_buff(0)
    , vulnerability_buff(0)
    , attack_buff(0)
    , remaining_energy(0)  {
    }
  Buff_(const ContainerAllocator& _alloc)
    : recovery_buff(0)
    , cooling_buff(0)
    , defence_buff(0)
    , vulnerability_buff(0)
    , attack_buff(0)
    , remaining_energy(0)  {
  (void)_alloc;
    }



   typedef uint8_t _recovery_buff_type;
  _recovery_buff_type recovery_buff;

   typedef uint8_t _cooling_buff_type;
  _cooling_buff_type cooling_buff;

   typedef uint8_t _defence_buff_type;
  _defence_buff_type defence_buff;

   typedef uint8_t _vulnerability_buff_type;
  _vulnerability_buff_type vulnerability_buff;

   typedef uint16_t _attack_buff_type;
  _attack_buff_type attack_buff;

   typedef uint8_t _remaining_energy_type;
  _remaining_energy_type remaining_energy;





  typedef boost::shared_ptr< ::rm_msgs::Buff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Buff_<ContainerAllocator> const> ConstPtr;

}; // struct Buff_

typedef ::rm_msgs::Buff_<std::allocator<void> > Buff;

typedef boost::shared_ptr< ::rm_msgs::Buff > BuffPtr;
typedef boost::shared_ptr< ::rm_msgs::Buff const> BuffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Buff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Buff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Buff_<ContainerAllocator1> & lhs, const ::rm_msgs::Buff_<ContainerAllocator2> & rhs)
{
  return lhs.recovery_buff == rhs.recovery_buff &&
    lhs.cooling_buff == rhs.cooling_buff &&
    lhs.defence_buff == rhs.defence_buff &&
    lhs.vulnerability_buff == rhs.vulnerability_buff &&
    lhs.attack_buff == rhs.attack_buff &&
    lhs.remaining_energy == rhs.remaining_energy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Buff_<ContainerAllocator1> & lhs, const ::rm_msgs::Buff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Buff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Buff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Buff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Buff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Buff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Buff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Buff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0350c419b72e90cb811a4148874b61cf";
  }

  static const char* value(const ::rm_msgs::Buff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0350c419b72e90cbULL;
  static const uint64_t static_value2 = 0x811a4148874b61cfULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Buff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Buff";
  }

  static const char* value(const ::rm_msgs::Buff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Buff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 recovery_buff\n"
"uint8 cooling_buff\n"
"uint8 defence_buff\n"
"uint8 vulnerability_buff\n"
"uint16 attack_buff\n"
"uint8 remaining_energy\n"
;
  }

  static const char* value(const ::rm_msgs::Buff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Buff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recovery_buff);
      stream.next(m.cooling_buff);
      stream.next(m.defence_buff);
      stream.next(m.vulnerability_buff);
      stream.next(m.attack_buff);
      stream.next(m.remaining_energy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Buff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Buff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Buff_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "recovery_buff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recovery_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cooling_buff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cooling_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "defence_buff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.defence_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vulnerability_buff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vulnerability_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "attack_buff: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.attack_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "remaining_energy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remaining_energy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_BUFF_H
