// Generated by gencpp from file rm_msgs/BusState.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_BUSSTATE_H
#define RM_MSGS_MESSAGE_BUSSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct BusState_
{
  typedef BusState_<ContainerAllocator> Type;

  BusState_()
    : stamp()
    , name()
    , isOnline()  {
    }
  BusState_(const ContainerAllocator& _alloc)
    : stamp()
    , name(_alloc)
    , isOnline(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _isOnline_type;
  _isOnline_type isOnline;





  typedef boost::shared_ptr< ::rm_msgs::BusState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::BusState_<ContainerAllocator> const> ConstPtr;

}; // struct BusState_

typedef ::rm_msgs::BusState_<std::allocator<void> > BusState;

typedef boost::shared_ptr< ::rm_msgs::BusState > BusStatePtr;
typedef boost::shared_ptr< ::rm_msgs::BusState const> BusStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::BusState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::BusState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::BusState_<ContainerAllocator1> & lhs, const ::rm_msgs::BusState_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.name == rhs.name &&
    lhs.isOnline == rhs.isOnline;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::BusState_<ContainerAllocator1> & lhs, const ::rm_msgs::BusState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::BusState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::BusState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::BusState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::BusState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::BusState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::BusState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::BusState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9d1975e503263409ee9d79a2a9249fe";
  }

  static const char* value(const ::rm_msgs::BusState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9d1975e50326340ULL;
  static const uint64_t static_value2 = 0x9ee9d79a2a9249feULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::BusState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/BusState";
  }

  static const char* value(const ::rm_msgs::BusState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::BusState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"\n"
"string[] name\n"
"bool[] isOnline\n"
;
  }

  static const char* value(const ::rm_msgs::BusState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::BusState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.name);
      stream.next(m.isOnline);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BusState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::BusState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::BusState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    if (v.name.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.name[i]);
    }
    if (v.name.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "isOnline: ";
    if (v.isOnline.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.isOnline.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.isOnline[i]);
    }
    if (v.isOnline.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_BUSSTATE_H
