// Generated by gencpp from file rm_msgs/ClientMapReceiveData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CLIENTMAPRECEIVEDATA_H
#define RM_MSGS_MESSAGE_CLIENTMAPRECEIVEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct ClientMapReceiveData_
{
  typedef ClientMapReceiveData_<ContainerAllocator> Type;

  ClientMapReceiveData_()
    : hero_position_x(0)
    , hero_position_y(0)
    , engineer_position_x(0)
    , engineer_position_y(0)
    , infantry_3_position_x(0)
    , infantry_3_position_y(0)
    , infantry_4_position_x(0)
    , infantry_4_position_y(0)
    , infantry_5_position_x(0)
    , infantry_5_position_y(0)
    , sentry_position_x(0)
    , sentry_position_y(0)
    , stamp()  {
    }
  ClientMapReceiveData_(const ContainerAllocator& _alloc)
    : hero_position_x(0)
    , hero_position_y(0)
    , engineer_position_x(0)
    , engineer_position_y(0)
    , infantry_3_position_x(0)
    , infantry_3_position_y(0)
    , infantry_4_position_x(0)
    , infantry_4_position_y(0)
    , infantry_5_position_x(0)
    , infantry_5_position_y(0)
    , sentry_position_x(0)
    , sentry_position_y(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint16_t _hero_position_x_type;
  _hero_position_x_type hero_position_x;

   typedef uint16_t _hero_position_y_type;
  _hero_position_y_type hero_position_y;

   typedef uint16_t _engineer_position_x_type;
  _engineer_position_x_type engineer_position_x;

   typedef uint16_t _engineer_position_y_type;
  _engineer_position_y_type engineer_position_y;

   typedef uint16_t _infantry_3_position_x_type;
  _infantry_3_position_x_type infantry_3_position_x;

   typedef uint16_t _infantry_3_position_y_type;
  _infantry_3_position_y_type infantry_3_position_y;

   typedef uint16_t _infantry_4_position_x_type;
  _infantry_4_position_x_type infantry_4_position_x;

   typedef uint16_t _infantry_4_position_y_type;
  _infantry_4_position_y_type infantry_4_position_y;

   typedef uint16_t _infantry_5_position_x_type;
  _infantry_5_position_x_type infantry_5_position_x;

   typedef uint16_t _infantry_5_position_y_type;
  _infantry_5_position_y_type infantry_5_position_y;

   typedef uint16_t _sentry_position_x_type;
  _sentry_position_x_type sentry_position_x;

   typedef uint16_t _sentry_position_y_type;
  _sentry_position_y_type sentry_position_y;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const> ConstPtr;

}; // struct ClientMapReceiveData_

typedef ::rm_msgs::ClientMapReceiveData_<std::allocator<void> > ClientMapReceiveData;

typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData > ClientMapReceiveDataPtr;
typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData const> ClientMapReceiveDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator1> & lhs, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator2> & rhs)
{
  return lhs.hero_position_x == rhs.hero_position_x &&
    lhs.hero_position_y == rhs.hero_position_y &&
    lhs.engineer_position_x == rhs.engineer_position_x &&
    lhs.engineer_position_y == rhs.engineer_position_y &&
    lhs.infantry_3_position_x == rhs.infantry_3_position_x &&
    lhs.infantry_3_position_y == rhs.infantry_3_position_y &&
    lhs.infantry_4_position_x == rhs.infantry_4_position_x &&
    lhs.infantry_4_position_y == rhs.infantry_4_position_y &&
    lhs.infantry_5_position_x == rhs.infantry_5_position_x &&
    lhs.infantry_5_position_y == rhs.infantry_5_position_y &&
    lhs.sentry_position_x == rhs.sentry_position_x &&
    lhs.sentry_position_y == rhs.sentry_position_y &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator1> & lhs, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "765860ed57371d5f547d7681e64c9b02";
  }

  static const char* value(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x765860ed57371d5fULL;
  static const uint64_t static_value2 = 0x547d7681e64c9b02ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ClientMapReceiveData";
  }

  static const char* value(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 hero_position_x\n"
"uint16 hero_position_y\n"
"uint16 engineer_position_x\n"
"uint16 engineer_position_y\n"
"uint16 infantry_3_position_x\n"
"uint16 infantry_3_position_y\n"
"uint16 infantry_4_position_x\n"
"uint16 infantry_4_position_y\n"
"uint16 infantry_5_position_x\n"
"uint16 infantry_5_position_y\n"
"uint16 sentry_position_x\n"
"uint16 sentry_position_y\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hero_position_x);
      stream.next(m.hero_position_y);
      stream.next(m.engineer_position_x);
      stream.next(m.engineer_position_y);
      stream.next(m.infantry_3_position_x);
      stream.next(m.infantry_3_position_y);
      stream.next(m.infantry_4_position_x);
      stream.next(m.infantry_4_position_y);
      stream.next(m.infantry_5_position_x);
      stream.next(m.infantry_5_position_y);
      stream.next(m.sentry_position_x);
      stream.next(m.sentry_position_y);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClientMapReceiveData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "hero_position_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hero_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hero_position_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hero_position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engineer_position_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.engineer_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engineer_position_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.engineer_position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "infantry_3_position_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.infantry_3_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "infantry_3_position_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.infantry_3_position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "infantry_4_position_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.infantry_4_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "infantry_4_position_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.infantry_4_position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "infantry_5_position_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.infantry_5_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "infantry_5_position_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.infantry_5_position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry_position_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sentry_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry_position_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sentry_position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CLIENTMAPRECEIVEDATA_H
