// Generated by gencpp from file rm_msgs/ClientMapSendData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CLIENTMAPSENDDATA_H
#define RM_MSGS_MESSAGE_CLIENTMAPSENDDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct ClientMapSendData_
{
  typedef ClientMapSendData_<ContainerAllocator> Type;

  ClientMapSendData_()
    : target_position_x(0.0)
    , target_position_y(0.0)
    , command_keyboard(0)
    , target_robot_ID(0)
    , cmd_source(0)  {
    }
  ClientMapSendData_(const ContainerAllocator& _alloc)
    : target_position_x(0.0)
    , target_position_y(0.0)
    , command_keyboard(0)
    , target_robot_ID(0)
    , cmd_source(0)  {
  (void)_alloc;
    }



   typedef float _target_position_x_type;
  _target_position_x_type target_position_x;

   typedef float _target_position_y_type;
  _target_position_y_type target_position_y;

   typedef uint8_t _command_keyboard_type;
  _command_keyboard_type command_keyboard;

   typedef uint8_t _target_robot_ID_type;
  _target_robot_ID_type target_robot_ID;

   typedef uint8_t _cmd_source_type;
  _cmd_source_type cmd_source;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(KEY_Q)
  #undef KEY_Q
#endif
#if defined(_WIN32) && defined(KEY_W)
  #undef KEY_W
#endif
#if defined(_WIN32) && defined(KEY_E)
  #undef KEY_E
#endif
#if defined(_WIN32) && defined(KEY_R)
  #undef KEY_R
#endif
#if defined(_WIN32) && defined(KEY_T)
  #undef KEY_T
#endif
#if defined(_WIN32) && defined(KEY_Y)
  #undef KEY_Y
#endif
#if defined(_WIN32) && defined(KEY_U)
  #undef KEY_U
#endif
#if defined(_WIN32) && defined(KEY_O)
  #undef KEY_O
#endif
#if defined(_WIN32) && defined(KEY_A)
  #undef KEY_A
#endif
#if defined(_WIN32) && defined(KEY_S)
  #undef KEY_S
#endif
#if defined(_WIN32) && defined(KEY_D)
  #undef KEY_D
#endif
#if defined(_WIN32) && defined(KEY_F)
  #undef KEY_F
#endif
#if defined(_WIN32) && defined(KEY_G)
  #undef KEY_G
#endif
#if defined(_WIN32) && defined(KEY_H)
  #undef KEY_H
#endif
#if defined(_WIN32) && defined(KEY_J)
  #undef KEY_J
#endif
#if defined(_WIN32) && defined(KEY_K)
  #undef KEY_K
#endif
#if defined(_WIN32) && defined(KEY_L)
  #undef KEY_L
#endif
#if defined(_WIN32) && defined(KEY_Z)
  #undef KEY_Z
#endif
#if defined(_WIN32) && defined(KEY_X)
  #undef KEY_X
#endif
#if defined(_WIN32) && defined(KEY_C)
  #undef KEY_C
#endif
#if defined(_WIN32) && defined(KEY_V)
  #undef KEY_V
#endif
#if defined(_WIN32) && defined(KEY_N)
  #undef KEY_N
#endif

  enum {
    KEY_Q = 81u,
    KEY_W = 87u,
    KEY_E = 69u,
    KEY_R = 82u,
    KEY_T = 84u,
    KEY_Y = 89u,
    KEY_U = 85u,
    KEY_O = 79u,
    KEY_A = 65u,
    KEY_S = 83u,
    KEY_D = 68u,
    KEY_F = 70u,
    KEY_G = 71u,
    KEY_H = 72u,
    KEY_J = 74u,
    KEY_K = 75u,
    KEY_L = 76u,
    KEY_Z = 90u,
    KEY_X = 88u,
    KEY_C = 67u,
    KEY_V = 86u,
    KEY_N = 78u,
  };


  typedef boost::shared_ptr< ::rm_msgs::ClientMapSendData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ClientMapSendData_<ContainerAllocator> const> ConstPtr;

}; // struct ClientMapSendData_

typedef ::rm_msgs::ClientMapSendData_<std::allocator<void> > ClientMapSendData;

typedef boost::shared_ptr< ::rm_msgs::ClientMapSendData > ClientMapSendDataPtr;
typedef boost::shared_ptr< ::rm_msgs::ClientMapSendData const> ClientMapSendDataConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ClientMapSendData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ClientMapSendData_<ContainerAllocator1> & lhs, const ::rm_msgs::ClientMapSendData_<ContainerAllocator2> & rhs)
{
  return lhs.target_position_x == rhs.target_position_x &&
    lhs.target_position_y == rhs.target_position_y &&
    lhs.command_keyboard == rhs.command_keyboard &&
    lhs.target_robot_ID == rhs.target_robot_ID &&
    lhs.cmd_source == rhs.cmd_source;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ClientMapSendData_<ContainerAllocator1> & lhs, const ::rm_msgs::ClientMapSendData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ClientMapSendData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ClientMapSendData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ClientMapSendData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aee27039134a834173f127a33eff61f7";
  }

  static const char* value(const ::rm_msgs::ClientMapSendData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaee27039134a8341ULL;
  static const uint64_t static_value2 = 0x73f127a33eff61f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ClientMapSendData";
  }

  static const char* value(const ::rm_msgs::ClientMapSendData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 KEY_Q = 81\n"
"uint8 KEY_W = 87\n"
"uint8 KEY_E = 69\n"
"uint8 KEY_R = 82\n"
"uint8 KEY_T = 84\n"
"uint8 KEY_Y = 89\n"
"uint8 KEY_U = 85\n"
"uint8 KEY_O = 79\n"
"\n"
"uint8 KEY_A = 65\n"
"uint8 KEY_S = 83\n"
"uint8 KEY_D = 68\n"
"uint8 KEY_F = 70\n"
"uint8 KEY_G = 71\n"
"uint8 KEY_H = 72\n"
"uint8 KEY_J = 74\n"
"uint8 KEY_K = 75\n"
"uint8 KEY_L = 76\n"
"\n"
"uint8 KEY_Z = 90\n"
"uint8 KEY_X = 88\n"
"uint8 KEY_C = 67\n"
"uint8 KEY_V = 86\n"
"uint8 KEY_N = 78\n"
"\n"
"float32 target_position_x\n"
"float32 target_position_y\n"
"uint8 command_keyboard\n"
"uint8 target_robot_ID\n"
"uint8 cmd_source\n"
;
  }

  static const char* value(const ::rm_msgs::ClientMapSendData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_position_x);
      stream.next(m.target_position_y);
      stream.next(m.command_keyboard);
      stream.next(m.target_robot_ID);
      stream.next(m.cmd_source);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClientMapSendData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ClientMapSendData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ClientMapSendData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_position_x: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_position_y: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command_keyboard: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command_keyboard);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_robot_ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_robot_ID);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_source);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CLIENTMAPSENDDATA_H
