// Generated by gencpp from file rm_msgs/CustomControllerData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CUSTOMCONTROLLERDATA_H
#define RM_MSGS_MESSAGE_CUSTOMCONTROLLERDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct CustomControllerData_
{
  typedef CustomControllerData_<ContainerAllocator> Type;

  CustomControllerData_()
    : encoder_data()
    , joystick_l_y_data(0)
    , joystick_l_x_data(0)
    , joystick_r_y_data(0)
    , joystick_r_x_data(0)
    , button_data()  {
      encoder_data.assign(0.0);

      button_data.assign(false);
  }
  CustomControllerData_(const ContainerAllocator& _alloc)
    : encoder_data()
    , joystick_l_y_data(0)
    , joystick_l_x_data(0)
    , joystick_r_y_data(0)
    , joystick_r_x_data(0)
    , button_data()  {
  (void)_alloc;
      encoder_data.assign(0.0);

      button_data.assign(false);
  }



   typedef boost::array<double, 6>  _encoder_data_type;
  _encoder_data_type encoder_data;

   typedef uint16_t _joystick_l_y_data_type;
  _joystick_l_y_data_type joystick_l_y_data;

   typedef uint16_t _joystick_l_x_data_type;
  _joystick_l_x_data_type joystick_l_x_data;

   typedef uint16_t _joystick_r_y_data_type;
  _joystick_r_y_data_type joystick_r_y_data;

   typedef uint16_t _joystick_r_x_data_type;
  _joystick_r_x_data_type joystick_r_x_data;

   typedef boost::array<uint8_t, 4>  _button_data_type;
  _button_data_type button_data;





  typedef boost::shared_ptr< ::rm_msgs::CustomControllerData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::CustomControllerData_<ContainerAllocator> const> ConstPtr;

}; // struct CustomControllerData_

typedef ::rm_msgs::CustomControllerData_<std::allocator<void> > CustomControllerData;

typedef boost::shared_ptr< ::rm_msgs::CustomControllerData > CustomControllerDataPtr;
typedef boost::shared_ptr< ::rm_msgs::CustomControllerData const> CustomControllerDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::CustomControllerData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::CustomControllerData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::CustomControllerData_<ContainerAllocator1> & lhs, const ::rm_msgs::CustomControllerData_<ContainerAllocator2> & rhs)
{
  return lhs.encoder_data == rhs.encoder_data &&
    lhs.joystick_l_y_data == rhs.joystick_l_y_data &&
    lhs.joystick_l_x_data == rhs.joystick_l_x_data &&
    lhs.joystick_r_y_data == rhs.joystick_r_y_data &&
    lhs.joystick_r_x_data == rhs.joystick_r_x_data &&
    lhs.button_data == rhs.button_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::CustomControllerData_<ContainerAllocator1> & lhs, const ::rm_msgs::CustomControllerData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::CustomControllerData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::CustomControllerData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::CustomControllerData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a85b28a60657f47c3215f53168ea534";
  }

  static const char* value(const ::rm_msgs::CustomControllerData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a85b28a60657f47ULL;
  static const uint64_t static_value2 = 0xc3215f53168ea534ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/CustomControllerData";
  }

  static const char* value(const ::rm_msgs::CustomControllerData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] encoder_data\n"
"\n"
"uint16 joystick_l_y_data\n"
"uint16 joystick_l_x_data\n"
"uint16 joystick_r_y_data\n"
"uint16 joystick_r_x_data\n"
"\n"
"bool[4] button_data\n"
;
  }

  static const char* value(const ::rm_msgs::CustomControllerData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder_data);
      stream.next(m.joystick_l_y_data);
      stream.next(m.joystick_l_x_data);
      stream.next(m.joystick_r_y_data);
      stream.next(m.joystick_r_x_data);
      stream.next(m.button_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomControllerData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::CustomControllerData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::CustomControllerData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "encoder_data: ";
    if (v.encoder_data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.encoder_data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.encoder_data[i]);
    }
    if (v.encoder_data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joystick_l_y_data: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.joystick_l_y_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joystick_l_x_data: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.joystick_l_x_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joystick_r_y_data: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.joystick_r_y_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joystick_r_x_data: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.joystick_r_x_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "button_data: ";
    if (v.button_data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.button_data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.button_data[i]);
    }
    if (v.button_data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CUSTOMCONTROLLERDATA_H
