// Generated by gencpp from file rm_msgs/DartInfo.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_DARTINFO_H
#define RM_MSGS_MESSAGE_DARTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct DartInfo_
{
  typedef DartInfo_<ContainerAllocator> Type;

  DartInfo_()
    : dart_remaining_time(0)
    , dart_last_aim_state(0)
    , enemy_total_hit_received(0)
    , dart_current_target(0)
    , stamp()  {
    }
  DartInfo_(const ContainerAllocator& _alloc)
    : dart_remaining_time(0)
    , dart_last_aim_state(0)
    , enemy_total_hit_received(0)
    , dart_current_target(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _dart_remaining_time_type;
  _dart_remaining_time_type dart_remaining_time;

   typedef uint8_t _dart_last_aim_state_type;
  _dart_last_aim_state_type dart_last_aim_state;

   typedef uint8_t _enemy_total_hit_received_type;
  _enemy_total_hit_received_type enemy_total_hit_received;

   typedef uint8_t _dart_current_target_type;
  _dart_current_target_type dart_current_target;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::DartInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::DartInfo_<ContainerAllocator> const> ConstPtr;

}; // struct DartInfo_

typedef ::rm_msgs::DartInfo_<std::allocator<void> > DartInfo;

typedef boost::shared_ptr< ::rm_msgs::DartInfo > DartInfoPtr;
typedef boost::shared_ptr< ::rm_msgs::DartInfo const> DartInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::DartInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::DartInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::DartInfo_<ContainerAllocator1> & lhs, const ::rm_msgs::DartInfo_<ContainerAllocator2> & rhs)
{
  return lhs.dart_remaining_time == rhs.dart_remaining_time &&
    lhs.dart_last_aim_state == rhs.dart_last_aim_state &&
    lhs.enemy_total_hit_received == rhs.enemy_total_hit_received &&
    lhs.dart_current_target == rhs.dart_current_target &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::DartInfo_<ContainerAllocator1> & lhs, const ::rm_msgs::DartInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::DartInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::DartInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::DartInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::DartInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::DartInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::DartInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::DartInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73e2079390bc6e9a5cb0850ee23279ca";
  }

  static const char* value(const ::rm_msgs::DartInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73e2079390bc6e9aULL;
  static const uint64_t static_value2 = 0x5cb0850ee23279caULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::DartInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/DartInfo";
  }

  static const char* value(const ::rm_msgs::DartInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::DartInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 dart_remaining_time\n"
"uint8 dart_last_aim_state\n"
"uint8 enemy_total_hit_received\n"
"uint8 dart_current_target\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::DartInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::DartInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dart_remaining_time);
      stream.next(m.dart_last_aim_state);
      stream.next(m.enemy_total_hit_received);
      stream.next(m.dart_current_target);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DartInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::DartInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::DartInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "dart_remaining_time: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dart_remaining_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dart_last_aim_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dart_last_aim_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_total_hit_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_total_hit_received);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dart_current_target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dart_current_target);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_DARTINFO_H
