// Generated by gencpp from file rm_msgs/EngineerUi.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ENGINEERUI_H
#define RM_MSGS_MESSAGE_ENGINEERUI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct EngineerUi_
{
  typedef EngineerUi_<ContainerAllocator> Type;

  EngineerUi_()
    : control_mode()
    , gripper_state()
    , ex_arm_state()
    , stone_num(0)
    , step_queue_name()
    , symbol(0)
    , stamp()  {
    }
  EngineerUi_(const ContainerAllocator& _alloc)
    : control_mode(_alloc)
    , gripper_state(_alloc)
    , ex_arm_state(_alloc)
    , stone_num(0)
    , step_queue_name(_alloc)
    , symbol(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _control_mode_type;
  _control_mode_type control_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _gripper_state_type;
  _gripper_state_type gripper_state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ex_arm_state_type;
  _ex_arm_state_type ex_arm_state;

   typedef uint32_t _stone_num_type;
  _stone_num_type stone_num;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _step_queue_name_type;
  _step_queue_name_type step_queue_name;

   typedef uint32_t _symbol_type;
  _symbol_type symbol;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::EngineerUi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::EngineerUi_<ContainerAllocator> const> ConstPtr;

}; // struct EngineerUi_

typedef ::rm_msgs::EngineerUi_<std::allocator<void> > EngineerUi;

typedef boost::shared_ptr< ::rm_msgs::EngineerUi > EngineerUiPtr;
typedef boost::shared_ptr< ::rm_msgs::EngineerUi const> EngineerUiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::EngineerUi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::EngineerUi_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::EngineerUi_<ContainerAllocator1> & lhs, const ::rm_msgs::EngineerUi_<ContainerAllocator2> & rhs)
{
  return lhs.control_mode == rhs.control_mode &&
    lhs.gripper_state == rhs.gripper_state &&
    lhs.ex_arm_state == rhs.ex_arm_state &&
    lhs.stone_num == rhs.stone_num &&
    lhs.step_queue_name == rhs.step_queue_name &&
    lhs.symbol == rhs.symbol &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::EngineerUi_<ContainerAllocator1> & lhs, const ::rm_msgs::EngineerUi_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::EngineerUi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::EngineerUi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::EngineerUi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::EngineerUi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::EngineerUi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::EngineerUi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::EngineerUi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d63975e3d07f2008b665b034a02c094f";
  }

  static const char* value(const ::rm_msgs::EngineerUi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd63975e3d07f2008ULL;
  static const uint64_t static_value2 = 0xb665b034a02c094fULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::EngineerUi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/EngineerUi";
  }

  static const char* value(const ::rm_msgs::EngineerUi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::EngineerUi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string control_mode\n"
"string gripper_state\n"
"string ex_arm_state\n"
"uint32 stone_num\n"
"\n"
"string step_queue_name\n"
"uint32 symbol\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::EngineerUi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::EngineerUi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode);
      stream.next(m.gripper_state);
      stream.next(m.ex_arm_state);
      stream.next(m.stone_num);
      stream.next(m.step_queue_name);
      stream.next(m.symbol);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EngineerUi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::EngineerUi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::EngineerUi_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "control_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.control_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gripper_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.gripper_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ex_arm_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ex_arm_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stone_num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.stone_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "step_queue_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.step_queue_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "symbol: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.symbol);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ENGINEERUI_H
