// Generated by gencpp from file rm_msgs/EventData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_EVENTDATA_H
#define RM_MSGS_MESSAGE_EVENTDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct EventData_
{
  typedef EventData_<ContainerAllocator> Type;

  EventData_()
    : overlapping_supply_station_state(false)
    , nan_overlapping_supply_station_state(false)
    , supplier_zone_state(false)
    , small_power_rune_state(false)
    , large_power_rune_state(false)
    , central_elevated_ground_state(0)
    , trapezoidal_elevated_ground_state(0)
    , be_hit_time(0)
    , be_hit_target(0)
    , central_point_state(0)
    , own_fortress_state(0)
    , stamp()  {
    }
  EventData_(const ContainerAllocator& _alloc)
    : overlapping_supply_station_state(false)
    , nan_overlapping_supply_station_state(false)
    , supplier_zone_state(false)
    , small_power_rune_state(false)
    , large_power_rune_state(false)
    , central_elevated_ground_state(0)
    , trapezoidal_elevated_ground_state(0)
    , be_hit_time(0)
    , be_hit_target(0)
    , central_point_state(0)
    , own_fortress_state(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _overlapping_supply_station_state_type;
  _overlapping_supply_station_state_type overlapping_supply_station_state;

   typedef uint8_t _nan_overlapping_supply_station_state_type;
  _nan_overlapping_supply_station_state_type nan_overlapping_supply_station_state;

   typedef uint8_t _supplier_zone_state_type;
  _supplier_zone_state_type supplier_zone_state;

   typedef uint8_t _small_power_rune_state_type;
  _small_power_rune_state_type small_power_rune_state;

   typedef uint8_t _large_power_rune_state_type;
  _large_power_rune_state_type large_power_rune_state;

   typedef uint8_t _central_elevated_ground_state_type;
  _central_elevated_ground_state_type central_elevated_ground_state;

   typedef uint8_t _trapezoidal_elevated_ground_state_type;
  _trapezoidal_elevated_ground_state_type trapezoidal_elevated_ground_state;

   typedef uint16_t _be_hit_time_type;
  _be_hit_time_type be_hit_time;

   typedef uint8_t _be_hit_target_type;
  _be_hit_target_type be_hit_target;

   typedef uint8_t _central_point_state_type;
  _central_point_state_type central_point_state;

   typedef uint8_t _own_fortress_state_type;
  _own_fortress_state_type own_fortress_state;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::EventData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::EventData_<ContainerAllocator> const> ConstPtr;

}; // struct EventData_

typedef ::rm_msgs::EventData_<std::allocator<void> > EventData;

typedef boost::shared_ptr< ::rm_msgs::EventData > EventDataPtr;
typedef boost::shared_ptr< ::rm_msgs::EventData const> EventDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::EventData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::EventData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::EventData_<ContainerAllocator1> & lhs, const ::rm_msgs::EventData_<ContainerAllocator2> & rhs)
{
  return lhs.overlapping_supply_station_state == rhs.overlapping_supply_station_state &&
    lhs.nan_overlapping_supply_station_state == rhs.nan_overlapping_supply_station_state &&
    lhs.supplier_zone_state == rhs.supplier_zone_state &&
    lhs.small_power_rune_state == rhs.small_power_rune_state &&
    lhs.large_power_rune_state == rhs.large_power_rune_state &&
    lhs.central_elevated_ground_state == rhs.central_elevated_ground_state &&
    lhs.trapezoidal_elevated_ground_state == rhs.trapezoidal_elevated_ground_state &&
    lhs.be_hit_time == rhs.be_hit_time &&
    lhs.be_hit_target == rhs.be_hit_target &&
    lhs.central_point_state == rhs.central_point_state &&
    lhs.own_fortress_state == rhs.own_fortress_state &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::EventData_<ContainerAllocator1> & lhs, const ::rm_msgs::EventData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::EventData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::EventData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::EventData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::EventData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::EventData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::EventData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::EventData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e0fe7f33f8d70cbb516e24d1e30721c";
  }

  static const char* value(const ::rm_msgs::EventData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e0fe7f33f8d70cbULL;
  static const uint64_t static_value2 = 0xb516e24d1e30721cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::EventData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/EventData";
  }

  static const char* value(const ::rm_msgs::EventData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::EventData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool overlapping_supply_station_state\n"
"bool nan_overlapping_supply_station_state\n"
"bool supplier_zone_state\n"
"bool small_power_rune_state\n"
"bool large_power_rune_state\n"
"uint8 central_elevated_ground_state\n"
"uint8 trapezoidal_elevated_ground_state\n"
"uint16 be_hit_time\n"
"uint8 be_hit_target\n"
"uint8 central_point_state\n"
"uint8 own_fortress_state\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::EventData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::EventData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.overlapping_supply_station_state);
      stream.next(m.nan_overlapping_supply_station_state);
      stream.next(m.supplier_zone_state);
      stream.next(m.small_power_rune_state);
      stream.next(m.large_power_rune_state);
      stream.next(m.central_elevated_ground_state);
      stream.next(m.trapezoidal_elevated_ground_state);
      stream.next(m.be_hit_time);
      stream.next(m.be_hit_target);
      stream.next(m.central_point_state);
      stream.next(m.own_fortress_state);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EventData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::EventData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::EventData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "overlapping_supply_station_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overlapping_supply_station_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nan_overlapping_supply_station_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nan_overlapping_supply_station_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "supplier_zone_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.supplier_zone_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "small_power_rune_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.small_power_rune_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "large_power_rune_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.large_power_rune_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "central_elevated_ground_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.central_elevated_ground_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trapezoidal_elevated_ground_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trapezoidal_elevated_ground_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "be_hit_time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.be_hit_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "be_hit_target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.be_hit_target);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "central_point_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.central_point_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "own_fortress_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.own_fortress_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_EVENTDATA_H
