// Generated by gencpp from file rm_msgs/GimbalPosState.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_GIMBALPOSSTATE_H
#define RM_MSGS_MESSAGE_GIMBALPOSSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct GimbalPosState_
{
  typedef GimbalPosState_<ContainerAllocator> Type;

  GimbalPosState_()
    : header()
    , set_point(0.0)
    , set_point_dot(0.0)
    , process_value(0.0)
    , error(0.0)
    , command(0.0)  {
    }
  GimbalPosState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , set_point(0.0)
    , set_point_dot(0.0)
    , process_value(0.0)
    , error(0.0)
    , command(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _set_point_type;
  _set_point_type set_point;

   typedef double _set_point_dot_type;
  _set_point_dot_type set_point_dot;

   typedef double _process_value_type;
  _process_value_type process_value;

   typedef double _error_type;
  _error_type error;

   typedef double _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::rm_msgs::GimbalPosState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::GimbalPosState_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalPosState_

typedef ::rm_msgs::GimbalPosState_<std::allocator<void> > GimbalPosState;

typedef boost::shared_ptr< ::rm_msgs::GimbalPosState > GimbalPosStatePtr;
typedef boost::shared_ptr< ::rm_msgs::GimbalPosState const> GimbalPosStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::GimbalPosState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::GimbalPosState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::GimbalPosState_<ContainerAllocator1> & lhs, const ::rm_msgs::GimbalPosState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.set_point == rhs.set_point &&
    lhs.set_point_dot == rhs.set_point_dot &&
    lhs.process_value == rhs.process_value &&
    lhs.error == rhs.error &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::GimbalPosState_<ContainerAllocator1> & lhs, const ::rm_msgs::GimbalPosState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::GimbalPosState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::GimbalPosState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::GimbalPosState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8296607f8ca74414ef9d0745d5f23e5f";
  }

  static const char* value(const ::rm_msgs::GimbalPosState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8296607f8ca74414ULL;
  static const uint64_t static_value2 = 0xef9d0745d5f23e5fULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/GimbalPosState";
  }

  static const char* value(const ::rm_msgs::GimbalPosState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 set_point\n"
"float64 set_point_dot\n"
"float64 process_value\n"
"float64 error\n"
"float64 command\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rm_msgs::GimbalPosState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.set_point);
      stream.next(m.set_point_dot);
      stream.next(m.process_value);
      stream.next(m.error);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalPosState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::GimbalPosState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::GimbalPosState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "set_point: ";
    Printer<double>::stream(s, indent + "  ", v.set_point);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "set_point_dot: ";
    Printer<double>::stream(s, indent + "  ", v.set_point_dot);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "process_value: ";
    Printer<double>::stream(s, indent + "  ", v.process_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<double>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_GIMBALPOSSTATE_H
