// Generated by gencpp from file rm_msgs/LegCmd.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_LEGCMD_H
#define RM_MSGS_MESSAGE_LEGCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct LegCmd_
{
  typedef LegCmd_<ContainerAllocator> Type;

  LegCmd_()
    : jump(false)
    , leg_length(0.0)  {
    }
  LegCmd_(const ContainerAllocator& _alloc)
    : jump(false)
    , leg_length(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _jump_type;
  _jump_type jump;

   typedef double _leg_length_type;
  _leg_length_type leg_length;





  typedef boost::shared_ptr< ::rm_msgs::LegCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::LegCmd_<ContainerAllocator> const> ConstPtr;

}; // struct LegCmd_

typedef ::rm_msgs::LegCmd_<std::allocator<void> > LegCmd;

typedef boost::shared_ptr< ::rm_msgs::LegCmd > LegCmdPtr;
typedef boost::shared_ptr< ::rm_msgs::LegCmd const> LegCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::LegCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::LegCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::LegCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::LegCmd_<ContainerAllocator2> & rhs)
{
  return lhs.jump == rhs.jump &&
    lhs.leg_length == rhs.leg_length;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::LegCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::LegCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::LegCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::LegCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::LegCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::LegCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::LegCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::LegCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::LegCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88c1d23c403ffa8f3ded0d5c3447e4f";
  }

  static const char* value(const ::rm_msgs::LegCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88c1d23c403ffa8ULL;
  static const uint64_t static_value2 = 0xf3ded0d5c3447e4fULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::LegCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/LegCmd";
  }

  static const char* value(const ::rm_msgs::LegCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::LegCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool jump\n"
"float64 leg_length\n"
;
  }

  static const char* value(const ::rm_msgs::LegCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::LegCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jump);
      stream.next(m.leg_length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::LegCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::LegCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "jump: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.jump);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "leg_length: ";
    Printer<double>::stream(s, indent + "  ", v.leg_length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_LEGCMD_H
