// Generated by gencpp from file rm_msgs/LocalHeatState.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_LOCALHEATSTATE_H
#define RM_MSGS_MESSAGE_LOCALHEATSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct LocalHeatState_
{
  typedef LocalHeatState_<ContainerAllocator> Type;

  LocalHeatState_()
    : friction_speed(0.0)
    , friction_change_speed(0.0)
    , friction_change_speed_derivative(0.0)
    , has_shoot(false)
    , stamp()  {
    }
  LocalHeatState_(const ContainerAllocator& _alloc)
    : friction_speed(0.0)
    , friction_change_speed(0.0)
    , friction_change_speed_derivative(0.0)
    , has_shoot(false)
    , stamp()  {
  (void)_alloc;
    }



   typedef double _friction_speed_type;
  _friction_speed_type friction_speed;

   typedef double _friction_change_speed_type;
  _friction_change_speed_type friction_change_speed;

   typedef double _friction_change_speed_derivative_type;
  _friction_change_speed_derivative_type friction_change_speed_derivative;

   typedef uint8_t _has_shoot_type;
  _has_shoot_type has_shoot;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::LocalHeatState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::LocalHeatState_<ContainerAllocator> const> ConstPtr;

}; // struct LocalHeatState_

typedef ::rm_msgs::LocalHeatState_<std::allocator<void> > LocalHeatState;

typedef boost::shared_ptr< ::rm_msgs::LocalHeatState > LocalHeatStatePtr;
typedef boost::shared_ptr< ::rm_msgs::LocalHeatState const> LocalHeatStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::LocalHeatState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::LocalHeatState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::LocalHeatState_<ContainerAllocator1> & lhs, const ::rm_msgs::LocalHeatState_<ContainerAllocator2> & rhs)
{
  return lhs.friction_speed == rhs.friction_speed &&
    lhs.friction_change_speed == rhs.friction_change_speed &&
    lhs.friction_change_speed_derivative == rhs.friction_change_speed_derivative &&
    lhs.has_shoot == rhs.has_shoot &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::LocalHeatState_<ContainerAllocator1> & lhs, const ::rm_msgs::LocalHeatState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::LocalHeatState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::LocalHeatState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::LocalHeatState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29a8a14a26935854a78d9ab8fc58289b";
  }

  static const char* value(const ::rm_msgs::LocalHeatState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29a8a14a26935854ULL;
  static const uint64_t static_value2 = 0xa78d9ab8fc58289bULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/LocalHeatState";
  }

  static const char* value(const ::rm_msgs::LocalHeatState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 friction_speed\n"
"float64 friction_change_speed\n"
"float64 friction_change_speed_derivative\n"
"bool has_shoot\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::LocalHeatState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.friction_speed);
      stream.next(m.friction_change_speed);
      stream.next(m.friction_change_speed_derivative);
      stream.next(m.has_shoot);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalHeatState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::LocalHeatState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::LocalHeatState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "friction_speed: ";
    Printer<double>::stream(s, indent + "  ", v.friction_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "friction_change_speed: ";
    Printer<double>::stream(s, indent + "  ", v.friction_change_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "friction_change_speed_derivative: ";
    Printer<double>::stream(s, indent + "  ", v.friction_change_speed_derivative);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "has_shoot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_shoot);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_LOCALHEATSTATE_H
