// Generated by gencpp from file rm_msgs/RadarToSentry.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARTOSENTRY_H
#define RM_MSGS_MESSAGE_RADARTOSENTRY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarToSentry_
{
  typedef RadarToSentry_<ContainerAllocator> Type;

  RadarToSentry_()
    : robot_ID(0)
    , position_x(0.0)
    , position_y(0.0)
    , engineer_marked(false)  {
    }
  RadarToSentry_(const ContainerAllocator& _alloc)
    : robot_ID(0)
    , position_x(0.0)
    , position_y(0.0)
    , engineer_marked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _robot_ID_type;
  _robot_ID_type robot_ID;

   typedef float _position_x_type;
  _position_x_type position_x;

   typedef float _position_y_type;
  _position_y_type position_y;

   typedef uint8_t _engineer_marked_type;
  _engineer_marked_type engineer_marked;





  typedef boost::shared_ptr< ::rm_msgs::RadarToSentry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarToSentry_<ContainerAllocator> const> ConstPtr;

}; // struct RadarToSentry_

typedef ::rm_msgs::RadarToSentry_<std::allocator<void> > RadarToSentry;

typedef boost::shared_ptr< ::rm_msgs::RadarToSentry > RadarToSentryPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarToSentry const> RadarToSentryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarToSentry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarToSentry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarToSentry_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarToSentry_<ContainerAllocator2> & rhs)
{
  return lhs.robot_ID == rhs.robot_ID &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.engineer_marked == rhs.engineer_marked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarToSentry_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarToSentry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarToSentry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarToSentry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarToSentry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55598f76d4bb77ccd6286fc50e5b4aed";
  }

  static const char* value(const ::rm_msgs::RadarToSentry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55598f76d4bb77ccULL;
  static const uint64_t static_value2 = 0xd6286fc50e5b4aedULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarToSentry";
  }

  static const char* value(const ::rm_msgs::RadarToSentry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 robot_ID\n"
"float32 position_x\n"
"float32 position_y\n"
"bool engineer_marked\n"
;
  }

  static const char* value(const ::rm_msgs::RadarToSentry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_ID);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.engineer_marked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarToSentry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarToSentry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarToSentry_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "robot_ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_ID);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position_x: ";
    Printer<float>::stream(s, indent + "  ", v.position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position_y: ";
    Printer<float>::stream(s, indent + "  ", v.position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engineer_marked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.engineer_marked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARTOSENTRY_H
