// Generated by gencpp from file rm_msgs/SentryAttackingTarget.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SENTRYATTACKINGTARGET_H
#define RM_MSGS_MESSAGE_SENTRYATTACKINGTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct SentryAttackingTarget_
{
  typedef SentryAttackingTarget_<ContainerAllocator> Type;

  SentryAttackingTarget_()
    : target_robot_ID(0)
    , target_position_x(0.0)
    , target_position_y(0.0)  {
    }
  SentryAttackingTarget_(const ContainerAllocator& _alloc)
    : target_robot_ID(0)
    , target_position_x(0.0)
    , target_position_y(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _target_robot_ID_type;
  _target_robot_ID_type target_robot_ID;

   typedef float _target_position_x_type;
  _target_position_x_type target_position_x;

   typedef float _target_position_y_type;
  _target_position_y_type target_position_y;





  typedef boost::shared_ptr< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> const> ConstPtr;

}; // struct SentryAttackingTarget_

typedef ::rm_msgs::SentryAttackingTarget_<std::allocator<void> > SentryAttackingTarget;

typedef boost::shared_ptr< ::rm_msgs::SentryAttackingTarget > SentryAttackingTargetPtr;
typedef boost::shared_ptr< ::rm_msgs::SentryAttackingTarget const> SentryAttackingTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator1> & lhs, const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator2> & rhs)
{
  return lhs.target_robot_ID == rhs.target_robot_ID &&
    lhs.target_position_x == rhs.target_position_x &&
    lhs.target_position_y == rhs.target_position_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator1> & lhs, const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a40fa9feb588f965f643eb4bde597b4";
  }

  static const char* value(const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a40fa9feb588f96ULL;
  static const uint64_t static_value2 = 0x5f643eb4bde597b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/SentryAttackingTarget";
  }

  static const char* value(const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 target_robot_ID\n"
"float32 target_position_x\n"
"float32 target_position_y\n"
;
  }

  static const char* value(const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_robot_ID);
      stream.next(m.target_position_x);
      stream.next(m.target_position_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SentryAttackingTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::SentryAttackingTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::SentryAttackingTarget_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_robot_ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_robot_ID);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_position_x: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_position_y: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SENTRYATTACKINGTARGET_H
