// Generated by gencpp from file rm_msgs/SentryInfo.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SENTRYINFO_H
#define RM_MSGS_MESSAGE_SENTRYINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct SentryInfo_
{
  typedef SentryInfo_<ContainerAllocator> Type;

  SentryInfo_()
    : sentry_info(0)
    , is_out_of_war(false)
    , remaining_bullets_can_supply(0)  {
    }
  SentryInfo_(const ContainerAllocator& _alloc)
    : sentry_info(0)
    , is_out_of_war(false)
    , remaining_bullets_can_supply(0)  {
  (void)_alloc;
    }



   typedef uint32_t _sentry_info_type;
  _sentry_info_type sentry_info;

   typedef uint8_t _is_out_of_war_type;
  _is_out_of_war_type is_out_of_war;

   typedef uint16_t _remaining_bullets_can_supply_type;
  _remaining_bullets_can_supply_type remaining_bullets_can_supply;





  typedef boost::shared_ptr< ::rm_msgs::SentryInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::SentryInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SentryInfo_

typedef ::rm_msgs::SentryInfo_<std::allocator<void> > SentryInfo;

typedef boost::shared_ptr< ::rm_msgs::SentryInfo > SentryInfoPtr;
typedef boost::shared_ptr< ::rm_msgs::SentryInfo const> SentryInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::SentryInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::SentryInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::SentryInfo_<ContainerAllocator1> & lhs, const ::rm_msgs::SentryInfo_<ContainerAllocator2> & rhs)
{
  return lhs.sentry_info == rhs.sentry_info &&
    lhs.is_out_of_war == rhs.is_out_of_war &&
    lhs.remaining_bullets_can_supply == rhs.remaining_bullets_can_supply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::SentryInfo_<ContainerAllocator1> & lhs, const ::rm_msgs::SentryInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::SentryInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::SentryInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::SentryInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::SentryInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::SentryInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::SentryInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::SentryInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12d17492af26f6bdf5a621bccb488999";
  }

  static const char* value(const ::rm_msgs::SentryInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12d17492af26f6bdULL;
  static const uint64_t static_value2 = 0xf5a621bccb488999ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::SentryInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/SentryInfo";
  }

  static const char* value(const ::rm_msgs::SentryInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::SentryInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 sentry_info\n"
"bool is_out_of_war\n"
"uint16 remaining_bullets_can_supply\n"
;
  }

  static const char* value(const ::rm_msgs::SentryInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::SentryInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentry_info);
      stream.next(m.is_out_of_war);
      stream.next(m.remaining_bullets_can_supply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SentryInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::SentryInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::SentryInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sentry_info: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sentry_info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_out_of_war: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_out_of_war);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "remaining_bullets_can_supply: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.remaining_bullets_can_supply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SENTRYINFO_H
