// Generated by gencpp from file rm_msgs/SentryCmd.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SENTRYCMD_H
#define RM_MSGS_MESSAGE_SENTRYCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct SentryCmd_
{
  typedef SentryCmd_<ContainerAllocator> Type;

  SentryCmd_()
    : sentry_info(0)  {
    }
  SentryCmd_(const ContainerAllocator& _alloc)
    : sentry_info(0)  {
  (void)_alloc;
    }



   typedef uint32_t _sentry_info_type;
  _sentry_info_type sentry_info;





  typedef boost::shared_ptr< ::rm_msgs::SentryCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::SentryCmd_<ContainerAllocator> const> ConstPtr;

}; // struct SentryCmd_

typedef ::rm_msgs::SentryCmd_<std::allocator<void> > SentryCmd;

typedef boost::shared_ptr< ::rm_msgs::SentryCmd > SentryCmdPtr;
typedef boost::shared_ptr< ::rm_msgs::SentryCmd const> SentryCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::SentryCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::SentryCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::SentryCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::SentryCmd_<ContainerAllocator2> & rhs)
{
  return lhs.sentry_info == rhs.sentry_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::SentryCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::SentryCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::SentryCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::SentryCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::SentryCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::SentryCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::SentryCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::SentryCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::SentryCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a21fe818ae8429588925e99460baf95";
  }

  static const char* value(const ::rm_msgs::SentryCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a21fe818ae84295ULL;
  static const uint64_t static_value2 = 0x88925e99460baf95ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::SentryCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/SentryCmd";
  }

  static const char* value(const ::rm_msgs::SentryCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::SentryCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 sentry_info\n"
;
  }

  static const char* value(const ::rm_msgs::SentryCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::SentryCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentry_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SentryCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::SentryCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::SentryCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sentry_info: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sentry_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SENTRYCMD_H
