// Generated by gencpp from file rm_msgs/ShootBeforehandCmd.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SHOOTBEFOREHANDCMD_H
#define RM_MSGS_MESSAGE_SHOOTBEFOREHANDCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct ShootBeforehandCmd_
{
  typedef ShootBeforehandCmd_<ContainerAllocator> Type;

  ShootBeforehandCmd_()
    : cmd(0)
    , stamp()  {
    }
  ShootBeforehandCmd_(const ContainerAllocator& _alloc)
    : cmd(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(BAN_SHOOT)
  #undef BAN_SHOOT
#endif
#if defined(_WIN32) && defined(JUDGE_BY_ERROR)
  #undef JUDGE_BY_ERROR
#endif
#if defined(_WIN32) && defined(ALLOW_SHOOT)
  #undef ALLOW_SHOOT
#endif

  enum {
    BAN_SHOOT = 0u,
    JUDGE_BY_ERROR = 1u,
    ALLOW_SHOOT = 2u,
  };


  typedef boost::shared_ptr< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ShootBeforehandCmd_

typedef ::rm_msgs::ShootBeforehandCmd_<std::allocator<void> > ShootBeforehandCmd;

typedef boost::shared_ptr< ::rm_msgs::ShootBeforehandCmd > ShootBeforehandCmdPtr;
typedef boost::shared_ptr< ::rm_msgs::ShootBeforehandCmd const> ShootBeforehandCmdConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d0971a7e1340988ce149c76e012d34d";
  }

  static const char* value(const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d0971a7e1340988ULL;
  static const uint64_t static_value2 = 0xce149c76e012d34dULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ShootBeforehandCmd";
  }

  static const char* value(const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 BAN_SHOOT = 0\n"
"uint8 JUDGE_BY_ERROR = 1\n"
"uint8 ALLOW_SHOOT = 2\n"
"\n"
"uint8 cmd\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootBeforehandCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ShootBeforehandCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SHOOTBEFOREHANDCMD_H
