// Generated by gencpp from file rm_msgs/VTKeyboardMouseData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_VTKEYBOARDMOUSEDATA_H
#define RM_MSGS_MESSAGE_VTKEYBOARDMOUSEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct VTKeyboardMouseData_
{
  typedef VTKeyboardMouseData_<ContainerAllocator> Type;

  VTKeyboardMouseData_()
    : mouse_x(0)
    , mouse_y(0)
    , mouse_z(0)
    , left_button_down(false)
    , right_button_down(false)
    , key_w(false)
    , key_s(false)
    , key_a(false)
    , key_d(false)
    , key_shift(false)
    , key_ctrl(false)
    , key_q(false)
    , key_e(false)
    , key_r(false)
    , key_f(false)
    , key_g(false)
    , key_z(false)
    , key_x(false)
    , key_c(false)
    , key_v(false)
    , key_b(false)  {
    }
  VTKeyboardMouseData_(const ContainerAllocator& _alloc)
    : mouse_x(0)
    , mouse_y(0)
    , mouse_z(0)
    , left_button_down(false)
    , right_button_down(false)
    , key_w(false)
    , key_s(false)
    , key_a(false)
    , key_d(false)
    , key_shift(false)
    , key_ctrl(false)
    , key_q(false)
    , key_e(false)
    , key_r(false)
    , key_f(false)
    , key_g(false)
    , key_z(false)
    , key_x(false)
    , key_c(false)
    , key_v(false)
    , key_b(false)  {
  (void)_alloc;
    }



   typedef int16_t _mouse_x_type;
  _mouse_x_type mouse_x;

   typedef int16_t _mouse_y_type;
  _mouse_y_type mouse_y;

   typedef int16_t _mouse_z_type;
  _mouse_z_type mouse_z;

   typedef uint8_t _left_button_down_type;
  _left_button_down_type left_button_down;

   typedef uint8_t _right_button_down_type;
  _right_button_down_type right_button_down;

   typedef uint8_t _key_w_type;
  _key_w_type key_w;

   typedef uint8_t _key_s_type;
  _key_s_type key_s;

   typedef uint8_t _key_a_type;
  _key_a_type key_a;

   typedef uint8_t _key_d_type;
  _key_d_type key_d;

   typedef uint8_t _key_shift_type;
  _key_shift_type key_shift;

   typedef uint8_t _key_ctrl_type;
  _key_ctrl_type key_ctrl;

   typedef uint8_t _key_q_type;
  _key_q_type key_q;

   typedef uint8_t _key_e_type;
  _key_e_type key_e;

   typedef uint8_t _key_r_type;
  _key_r_type key_r;

   typedef uint8_t _key_f_type;
  _key_f_type key_f;

   typedef uint8_t _key_g_type;
  _key_g_type key_g;

   typedef uint8_t _key_z_type;
  _key_z_type key_z;

   typedef uint8_t _key_x_type;
  _key_x_type key_x;

   typedef uint8_t _key_c_type;
  _key_c_type key_c;

   typedef uint8_t _key_v_type;
  _key_v_type key_v;

   typedef uint8_t _key_b_type;
  _key_b_type key_b;





  typedef boost::shared_ptr< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> const> ConstPtr;

}; // struct VTKeyboardMouseData_

typedef ::rm_msgs::VTKeyboardMouseData_<std::allocator<void> > VTKeyboardMouseData;

typedef boost::shared_ptr< ::rm_msgs::VTKeyboardMouseData > VTKeyboardMouseDataPtr;
typedef boost::shared_ptr< ::rm_msgs::VTKeyboardMouseData const> VTKeyboardMouseDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator1> & lhs, const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator2> & rhs)
{
  return lhs.mouse_x == rhs.mouse_x &&
    lhs.mouse_y == rhs.mouse_y &&
    lhs.mouse_z == rhs.mouse_z &&
    lhs.left_button_down == rhs.left_button_down &&
    lhs.right_button_down == rhs.right_button_down &&
    lhs.key_w == rhs.key_w &&
    lhs.key_s == rhs.key_s &&
    lhs.key_a == rhs.key_a &&
    lhs.key_d == rhs.key_d &&
    lhs.key_shift == rhs.key_shift &&
    lhs.key_ctrl == rhs.key_ctrl &&
    lhs.key_q == rhs.key_q &&
    lhs.key_e == rhs.key_e &&
    lhs.key_r == rhs.key_r &&
    lhs.key_f == rhs.key_f &&
    lhs.key_g == rhs.key_g &&
    lhs.key_z == rhs.key_z &&
    lhs.key_x == rhs.key_x &&
    lhs.key_c == rhs.key_c &&
    lhs.key_v == rhs.key_v &&
    lhs.key_b == rhs.key_b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator1> & lhs, const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9f68e8d3ee2022670ec30249830ac1d";
  }

  static const char* value(const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9f68e8d3ee20226ULL;
  static const uint64_t static_value2 = 0x70ec30249830ac1dULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/VTKeyboardMouseData";
  }

  static const char* value(const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 mouse_x\n"
"int16 mouse_y\n"
"int16 mouse_z\n"
"bool left_button_down\n"
"bool right_button_down\n"
"\n"
"bool key_w\n"
"bool key_s\n"
"bool key_a\n"
"bool key_d\n"
"bool key_shift\n"
"bool key_ctrl\n"
"bool key_q\n"
"bool key_e\n"
"bool key_r\n"
"bool key_f\n"
"bool key_g\n"
"bool key_z\n"
"bool key_x\n"
"bool key_c\n"
"bool key_v\n"
"bool key_b\n"
;
  }

  static const char* value(const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mouse_x);
      stream.next(m.mouse_y);
      stream.next(m.mouse_z);
      stream.next(m.left_button_down);
      stream.next(m.right_button_down);
      stream.next(m.key_w);
      stream.next(m.key_s);
      stream.next(m.key_a);
      stream.next(m.key_d);
      stream.next(m.key_shift);
      stream.next(m.key_ctrl);
      stream.next(m.key_q);
      stream.next(m.key_e);
      stream.next(m.key_r);
      stream.next(m.key_f);
      stream.next(m.key_g);
      stream.next(m.key_z);
      stream.next(m.key_x);
      stream.next(m.key_c);
      stream.next(m.key_v);
      stream.next(m.key_b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VTKeyboardMouseData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::VTKeyboardMouseData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mouse_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mouse_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mouse_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mouse_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_button_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_button_down);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_button_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_button_down);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_w: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_s: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_a);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_shift: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_shift);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_ctrl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_ctrl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_q: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_q);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_e: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_e);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_f: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_f);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_c: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_c);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_v: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_v);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_VTKEYBOARDMOUSEDATA_H
