// Generated by gencpp from file rm_msgs/VTReceiverControlData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_VTRECEIVERCONTROLDATA_H
#define RM_MSGS_MESSAGE_VTRECEIVERCONTROLDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct VTReceiverControlData_
{
  typedef VTReceiverControlData_<ContainerAllocator> Type;

  VTReceiverControlData_()
    : joystick_r_x(0.0)
    , joystick_r_y(0.0)
    , joystick_l_y(0.0)
    , joystick_l_x(0.0)
    , mode_switch(0)
    , pause_button(false)
    , custom_button_l(false)
    , custom_button_r(false)
    , wheel(0.0)
    , trigger(false)
    , mouse_x(0)
    , mouse_y(0)
    , mouse_wheel(0)
    , mouse_left_down(false)
    , mouse_right_down(false)
    , mouse_mid_down(false)
    , key_w(false)
    , key_s(false)
    , key_a(false)
    , key_d(false)
    , key_shift(false)
    , key_ctrl(false)
    , key_q(false)
    , key_e(false)
    , key_r(false)
    , key_f(false)
    , key_g(false)
    , key_z(false)
    , key_x(false)
    , key_c(false)
    , key_v(false)
    , key_b(false)  {
    }
  VTReceiverControlData_(const ContainerAllocator& _alloc)
    : joystick_r_x(0.0)
    , joystick_r_y(0.0)
    , joystick_l_y(0.0)
    , joystick_l_x(0.0)
    , mode_switch(0)
    , pause_button(false)
    , custom_button_l(false)
    , custom_button_r(false)
    , wheel(0.0)
    , trigger(false)
    , mouse_x(0)
    , mouse_y(0)
    , mouse_wheel(0)
    , mouse_left_down(false)
    , mouse_right_down(false)
    , mouse_mid_down(false)
    , key_w(false)
    , key_s(false)
    , key_a(false)
    , key_d(false)
    , key_shift(false)
    , key_ctrl(false)
    , key_q(false)
    , key_e(false)
    , key_r(false)
    , key_f(false)
    , key_g(false)
    , key_z(false)
    , key_x(false)
    , key_c(false)
    , key_v(false)
    , key_b(false)  {
  (void)_alloc;
    }



   typedef double _joystick_r_x_type;
  _joystick_r_x_type joystick_r_x;

   typedef double _joystick_r_y_type;
  _joystick_r_y_type joystick_r_y;

   typedef double _joystick_l_y_type;
  _joystick_l_y_type joystick_l_y;

   typedef double _joystick_l_x_type;
  _joystick_l_x_type joystick_l_x;

   typedef uint8_t _mode_switch_type;
  _mode_switch_type mode_switch;

   typedef uint8_t _pause_button_type;
  _pause_button_type pause_button;

   typedef uint8_t _custom_button_l_type;
  _custom_button_l_type custom_button_l;

   typedef uint8_t _custom_button_r_type;
  _custom_button_r_type custom_button_r;

   typedef double _wheel_type;
  _wheel_type wheel;

   typedef uint8_t _trigger_type;
  _trigger_type trigger;

   typedef int16_t _mouse_x_type;
  _mouse_x_type mouse_x;

   typedef int16_t _mouse_y_type;
  _mouse_y_type mouse_y;

   typedef int16_t _mouse_wheel_type;
  _mouse_wheel_type mouse_wheel;

   typedef uint8_t _mouse_left_down_type;
  _mouse_left_down_type mouse_left_down;

   typedef uint8_t _mouse_right_down_type;
  _mouse_right_down_type mouse_right_down;

   typedef uint8_t _mouse_mid_down_type;
  _mouse_mid_down_type mouse_mid_down;

   typedef uint8_t _key_w_type;
  _key_w_type key_w;

   typedef uint8_t _key_s_type;
  _key_s_type key_s;

   typedef uint8_t _key_a_type;
  _key_a_type key_a;

   typedef uint8_t _key_d_type;
  _key_d_type key_d;

   typedef uint8_t _key_shift_type;
  _key_shift_type key_shift;

   typedef uint8_t _key_ctrl_type;
  _key_ctrl_type key_ctrl;

   typedef uint8_t _key_q_type;
  _key_q_type key_q;

   typedef uint8_t _key_e_type;
  _key_e_type key_e;

   typedef uint8_t _key_r_type;
  _key_r_type key_r;

   typedef uint8_t _key_f_type;
  _key_f_type key_f;

   typedef uint8_t _key_g_type;
  _key_g_type key_g;

   typedef uint8_t _key_z_type;
  _key_z_type key_z;

   typedef uint8_t _key_x_type;
  _key_x_type key_x;

   typedef uint8_t _key_c_type;
  _key_c_type key_c;

   typedef uint8_t _key_v_type;
  _key_v_type key_v;

   typedef uint8_t _key_b_type;
  _key_b_type key_b;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_C)
  #undef MODE_C
#endif
#if defined(_WIN32) && defined(MODE_N)
  #undef MODE_N
#endif
#if defined(_WIN32) && defined(MODE_S)
  #undef MODE_S
#endif

  enum {
    MODE_C = 0u,
    MODE_N = 1u,
    MODE_S = 2u,
  };


  typedef boost::shared_ptr< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> const> ConstPtr;

}; // struct VTReceiverControlData_

typedef ::rm_msgs::VTReceiverControlData_<std::allocator<void> > VTReceiverControlData;

typedef boost::shared_ptr< ::rm_msgs::VTReceiverControlData > VTReceiverControlDataPtr;
typedef boost::shared_ptr< ::rm_msgs::VTReceiverControlData const> VTReceiverControlDataConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::VTReceiverControlData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::VTReceiverControlData_<ContainerAllocator1> & lhs, const ::rm_msgs::VTReceiverControlData_<ContainerAllocator2> & rhs)
{
  return lhs.joystick_r_x == rhs.joystick_r_x &&
    lhs.joystick_r_y == rhs.joystick_r_y &&
    lhs.joystick_l_y == rhs.joystick_l_y &&
    lhs.joystick_l_x == rhs.joystick_l_x &&
    lhs.mode_switch == rhs.mode_switch &&
    lhs.pause_button == rhs.pause_button &&
    lhs.custom_button_l == rhs.custom_button_l &&
    lhs.custom_button_r == rhs.custom_button_r &&
    lhs.wheel == rhs.wheel &&
    lhs.trigger == rhs.trigger &&
    lhs.mouse_x == rhs.mouse_x &&
    lhs.mouse_y == rhs.mouse_y &&
    lhs.mouse_wheel == rhs.mouse_wheel &&
    lhs.mouse_left_down == rhs.mouse_left_down &&
    lhs.mouse_right_down == rhs.mouse_right_down &&
    lhs.mouse_mid_down == rhs.mouse_mid_down &&
    lhs.key_w == rhs.key_w &&
    lhs.key_s == rhs.key_s &&
    lhs.key_a == rhs.key_a &&
    lhs.key_d == rhs.key_d &&
    lhs.key_shift == rhs.key_shift &&
    lhs.key_ctrl == rhs.key_ctrl &&
    lhs.key_q == rhs.key_q &&
    lhs.key_e == rhs.key_e &&
    lhs.key_r == rhs.key_r &&
    lhs.key_f == rhs.key_f &&
    lhs.key_g == rhs.key_g &&
    lhs.key_z == rhs.key_z &&
    lhs.key_x == rhs.key_x &&
    lhs.key_c == rhs.key_c &&
    lhs.key_v == rhs.key_v &&
    lhs.key_b == rhs.key_b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::VTReceiverControlData_<ContainerAllocator1> & lhs, const ::rm_msgs::VTReceiverControlData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccb3d14b76ed93d4c7a7597427ff5b6f";
  }

  static const char* value(const ::rm_msgs::VTReceiverControlData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccb3d14b76ed93d4ULL;
  static const uint64_t static_value2 = 0xc7a7597427ff5b6fULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/VTReceiverControlData";
  }

  static const char* value(const ::rm_msgs::VTReceiverControlData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 joystick_r_x\n"
"float64 joystick_r_y\n"
"float64 joystick_l_y\n"
"float64 joystick_l_x\n"
"\n"
"uint8 mode_switch\n"
"uint8 MODE_C = 0\n"
"uint8 MODE_N = 1\n"
"uint8 MODE_S = 2\n"
"\n"
"bool pause_button\n"
"bool custom_button_l\n"
"bool custom_button_r\n"
"float64 wheel\n"
"bool trigger\n"
"\n"
"int16 mouse_x\n"
"int16 mouse_y\n"
"int16 mouse_wheel\n"
"bool mouse_left_down\n"
"bool mouse_right_down\n"
"bool mouse_mid_down\n"
"\n"
"bool key_w\n"
"bool key_s\n"
"bool key_a\n"
"bool key_d\n"
"bool key_shift\n"
"bool key_ctrl\n"
"bool key_q\n"
"bool key_e\n"
"bool key_r\n"
"bool key_f\n"
"bool key_g\n"
"bool key_z\n"
"bool key_x\n"
"bool key_c\n"
"bool key_v\n"
"bool key_b\n"
;
  }

  static const char* value(const ::rm_msgs::VTReceiverControlData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joystick_r_x);
      stream.next(m.joystick_r_y);
      stream.next(m.joystick_l_y);
      stream.next(m.joystick_l_x);
      stream.next(m.mode_switch);
      stream.next(m.pause_button);
      stream.next(m.custom_button_l);
      stream.next(m.custom_button_r);
      stream.next(m.wheel);
      stream.next(m.trigger);
      stream.next(m.mouse_x);
      stream.next(m.mouse_y);
      stream.next(m.mouse_wheel);
      stream.next(m.mouse_left_down);
      stream.next(m.mouse_right_down);
      stream.next(m.mouse_mid_down);
      stream.next(m.key_w);
      stream.next(m.key_s);
      stream.next(m.key_a);
      stream.next(m.key_d);
      stream.next(m.key_shift);
      stream.next(m.key_ctrl);
      stream.next(m.key_q);
      stream.next(m.key_e);
      stream.next(m.key_r);
      stream.next(m.key_f);
      stream.next(m.key_g);
      stream.next(m.key_z);
      stream.next(m.key_x);
      stream.next(m.key_c);
      stream.next(m.key_v);
      stream.next(m.key_b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VTReceiverControlData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::VTReceiverControlData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::VTReceiverControlData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joystick_r_x: ";
    Printer<double>::stream(s, indent + "  ", v.joystick_r_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joystick_r_y: ";
    Printer<double>::stream(s, indent + "  ", v.joystick_r_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joystick_l_y: ";
    Printer<double>::stream(s, indent + "  ", v.joystick_l_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joystick_l_x: ";
    Printer<double>::stream(s, indent + "  ", v.joystick_l_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode_switch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode_switch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pause_button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pause_button);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "custom_button_l: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.custom_button_l);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "custom_button_r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.custom_button_r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel: ";
    Printer<double>::stream(s, indent + "  ", v.wheel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trigger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mouse_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mouse_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_wheel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mouse_wheel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_left_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mouse_left_down);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_right_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mouse_right_down);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mouse_mid_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mouse_mid_down);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_w: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_s: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_a);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_shift: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_shift);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_ctrl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_ctrl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_q: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_q);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_e: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_e);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_f: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_f);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_g);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_c: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_c);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_v: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_v);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "key_b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.key_b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_VTRECEIVERCONTROLDATA_H
