# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sentry_chassis_controller/ChassisState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ChassisState(genpy.Message):
  _md5sum = "be09b6eddd3e724282cde2412802ba78"
  _type = "sentry_chassis_controller/ChassisState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# 底盘状态消息
Header header

# 指令速度
float64 cmd_vx
float64 cmd_vy
float64 cmd_wz

# 轮子期望转速 (rad/s)
float64[4] desired_wheel_speeds
# 轮子实际转速 (rad/s)
float64[4] actual_wheel_speeds

# 轮子期望转向角度 (rad)
float64[4] desired_steering_angles
# 轮子实际转向角度 (rad)
float64[4] actual_steering_angles

# 轮子控制力矩
float64[4] wheel_efforts
# 转向控制力矩
float64[4] steering_efforts

# 是否接收到有效指令
bool cmd_vel_active
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','cmd_vx','cmd_vy','cmd_wz','desired_wheel_speeds','actual_wheel_speeds','desired_steering_angles','actual_steering_angles','wheel_efforts','steering_efforts','cmd_vel_active']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64[4]','float64[4]','float64[4]','float64[4]','float64[4]','float64[4]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,cmd_vx,cmd_vy,cmd_wz,desired_wheel_speeds,actual_wheel_speeds,desired_steering_angles,actual_steering_angles,wheel_efforts,steering_efforts,cmd_vel_active

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChassisState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cmd_vx is None:
        self.cmd_vx = 0.
      if self.cmd_vy is None:
        self.cmd_vy = 0.
      if self.cmd_wz is None:
        self.cmd_wz = 0.
      if self.desired_wheel_speeds is None:
        self.desired_wheel_speeds = [0.] * 4
      if self.actual_wheel_speeds is None:
        self.actual_wheel_speeds = [0.] * 4
      if self.desired_steering_angles is None:
        self.desired_steering_angles = [0.] * 4
      if self.actual_steering_angles is None:
        self.actual_steering_angles = [0.] * 4
      if self.wheel_efforts is None:
        self.wheel_efforts = [0.] * 4
      if self.steering_efforts is None:
        self.steering_efforts = [0.] * 4
      if self.cmd_vel_active is None:
        self.cmd_vel_active = False
    else:
      self.header = std_msgs.msg.Header()
      self.cmd_vx = 0.
      self.cmd_vy = 0.
      self.cmd_wz = 0.
      self.desired_wheel_speeds = [0.] * 4
      self.actual_wheel_speeds = [0.] * 4
      self.desired_steering_angles = [0.] * 4
      self.actual_steering_angles = [0.] * 4
      self.wheel_efforts = [0.] * 4
      self.steering_efforts = [0.] * 4
      self.cmd_vel_active = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.cmd_vx, _x.cmd_vy, _x.cmd_wz))
      buff.write(_get_struct_4d().pack(*self.desired_wheel_speeds))
      buff.write(_get_struct_4d().pack(*self.actual_wheel_speeds))
      buff.write(_get_struct_4d().pack(*self.desired_steering_angles))
      buff.write(_get_struct_4d().pack(*self.actual_steering_angles))
      buff.write(_get_struct_4d().pack(*self.wheel_efforts))
      buff.write(_get_struct_4d().pack(*self.steering_efforts))
      _x = self.cmd_vel_active
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.cmd_vx, _x.cmd_vy, _x.cmd_wz,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 32
      self.desired_wheel_speeds = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 32
      self.actual_wheel_speeds = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 32
      self.desired_steering_angles = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 32
      self.actual_steering_angles = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 32
      self.wheel_efforts = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 32
      self.steering_efforts = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 1
      (self.cmd_vel_active,) = _get_struct_B().unpack(str[start:end])
      self.cmd_vel_active = bool(self.cmd_vel_active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.cmd_vx, _x.cmd_vy, _x.cmd_wz))
      buff.write(self.desired_wheel_speeds.tostring())
      buff.write(self.actual_wheel_speeds.tostring())
      buff.write(self.desired_steering_angles.tostring())
      buff.write(self.actual_steering_angles.tostring())
      buff.write(self.wheel_efforts.tostring())
      buff.write(self.steering_efforts.tostring())
      _x = self.cmd_vel_active
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.cmd_vx, _x.cmd_vy, _x.cmd_wz,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 32
      self.desired_wheel_speeds = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      start = end
      end += 32
      self.actual_wheel_speeds = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      start = end
      end += 32
      self.desired_steering_angles = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      start = end
      end += 32
      self.actual_steering_angles = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      start = end
      end += 32
      self.wheel_efforts = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      start = end
      end += 32
      self.steering_efforts = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      start = end
      end += 1
      (self.cmd_vel_active,) = _get_struct_B().unpack(str[start:end])
      self.cmd_vel_active = bool(self.cmd_vel_active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
