# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Buff.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Buff(genpy.Message):
  _md5sum = "0350c419b72e90cb811a4148874b61cf"
  _type = "rm_msgs/Buff"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 recovery_buff
uint8 cooling_buff
uint8 defence_buff
uint8 vulnerability_buff
uint16 attack_buff
uint8 remaining_energy
"""
  __slots__ = ['recovery_buff','cooling_buff','defence_buff','vulnerability_buff','attack_buff','remaining_energy']
  _slot_types = ['uint8','uint8','uint8','uint8','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       recovery_buff,cooling_buff,defence_buff,vulnerability_buff,attack_buff,remaining_energy

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Buff, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.recovery_buff is None:
        self.recovery_buff = 0
      if self.cooling_buff is None:
        self.cooling_buff = 0
      if self.defence_buff is None:
        self.defence_buff = 0
      if self.vulnerability_buff is None:
        self.vulnerability_buff = 0
      if self.attack_buff is None:
        self.attack_buff = 0
      if self.remaining_energy is None:
        self.remaining_energy = 0
    else:
      self.recovery_buff = 0
      self.cooling_buff = 0
      self.defence_buff = 0
      self.vulnerability_buff = 0
      self.attack_buff = 0
      self.remaining_energy = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4BHB().pack(_x.recovery_buff, _x.cooling_buff, _x.defence_buff, _x.vulnerability_buff, _x.attack_buff, _x.remaining_energy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.recovery_buff, _x.cooling_buff, _x.defence_buff, _x.vulnerability_buff, _x.attack_buff, _x.remaining_energy,) = _get_struct_4BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4BHB().pack(_x.recovery_buff, _x.cooling_buff, _x.defence_buff, _x.vulnerability_buff, _x.attack_buff, _x.remaining_energy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.recovery_buff, _x.cooling_buff, _x.defence_buff, _x.vulnerability_buff, _x.attack_buff, _x.remaining_energy,) = _get_struct_4BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4BHB = None
def _get_struct_4BHB():
    global _struct_4BHB
    if _struct_4BHB is None:
        _struct_4BHB = struct.Struct("<4BHB")
    return _struct_4BHB
