# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/CustomControllerData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CustomControllerData(genpy.Message):
  _md5sum = "5a85b28a60657f47c3215f53168ea534"
  _type = "rm_msgs/CustomControllerData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64[6] encoder_data

uint16 joystick_l_y_data
uint16 joystick_l_x_data
uint16 joystick_r_y_data
uint16 joystick_r_x_data

bool[4] button_data
"""
  __slots__ = ['encoder_data','joystick_l_y_data','joystick_l_x_data','joystick_r_y_data','joystick_r_x_data','button_data']
  _slot_types = ['float64[6]','uint16','uint16','uint16','uint16','bool[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       encoder_data,joystick_l_y_data,joystick_l_x_data,joystick_r_y_data,joystick_r_x_data,button_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CustomControllerData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.encoder_data is None:
        self.encoder_data = [0.] * 6
      if self.joystick_l_y_data is None:
        self.joystick_l_y_data = 0
      if self.joystick_l_x_data is None:
        self.joystick_l_x_data = 0
      if self.joystick_r_y_data is None:
        self.joystick_r_y_data = 0
      if self.joystick_r_x_data is None:
        self.joystick_r_x_data = 0
      if self.button_data is None:
        self.button_data = [False] * 4
    else:
      self.encoder_data = [0.] * 6
      self.joystick_l_y_data = 0
      self.joystick_l_x_data = 0
      self.joystick_r_y_data = 0
      self.joystick_r_x_data = 0
      self.button_data = [False] * 4

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_6d().pack(*self.encoder_data))
      _x = self
      buff.write(_get_struct_4H().pack(_x.joystick_l_y_data, _x.joystick_l_x_data, _x.joystick_r_y_data, _x.joystick_r_x_data))
      buff.write(_get_struct_4B().pack(*self.button_data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 48
      self.encoder_data = _get_struct_6d().unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.joystick_l_y_data, _x.joystick_l_x_data, _x.joystick_r_y_data, _x.joystick_r_x_data,) = _get_struct_4H().unpack(str[start:end])
      start = end
      end += 4
      self.button_data = _get_struct_4B().unpack(str[start:end])
      self.button_data = list(map(bool, self.button_data))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.encoder_data.tostring())
      _x = self
      buff.write(_get_struct_4H().pack(_x.joystick_l_y_data, _x.joystick_l_x_data, _x.joystick_r_y_data, _x.joystick_r_x_data))
      buff.write(self.button_data.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 48
      self.encoder_data = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      _x = self
      start = end
      end += 8
      (_x.joystick_l_y_data, _x.joystick_l_x_data, _x.joystick_r_y_data, _x.joystick_r_x_data,) = _get_struct_4H().unpack(str[start:end])
      start = end
      end += 4
      self.button_data = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=4)
      self.button_data = list(map(bool, self.button_data))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
