# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Dart.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class Dart(genpy.Message):
  _md5sum = "a786858289d996b001b391aeda1dc1a4"
  _type = "rm_msgs/Dart"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 distance
int16 height
bool is_found
time stamp
"""
  __slots__ = ['distance','height','is_found','stamp']
  _slot_types = ['int16','int16','bool','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       distance,height,is_found,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Dart, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.distance is None:
        self.distance = 0
      if self.height is None:
        self.height = 0
      if self.is_found is None:
        self.is_found = False
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.distance = 0
      self.height = 0
      self.is_found = False
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2hB2I().pack(_x.distance, _x.height, _x.is_found, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.distance, _x.height, _x.is_found, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2hB2I().unpack(str[start:end])
      self.is_found = bool(self.is_found)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2hB2I().pack(_x.distance, _x.height, _x.is_found, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.distance, _x.height, _x.is_found, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_2hB2I().unpack(str[start:end])
      self.is_found = bool(self.is_found)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2hB2I = None
def _get_struct_2hB2I():
    global _struct_2hB2I
    if _struct_2hB2I is None:
        _struct_2hB2I = struct.Struct("<2hB2I")
    return _struct_2hB2I
