# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RfidStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class RfidStatus(genpy.Message):
  _md5sum = "7a24d6646cadd38d0b3cc4cdc34de56b"
  _type = "rm_msgs/RfidStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool base_buff_point_state
bool own_central_elevated_ground_state
bool enemy_central_elevated_ground_state
bool own_trapezoidal_elevated_ground_state
bool enemy_trapezoidal_elevated_ground_state
bool forward_own_terrain_span_buff_point_state
bool behind_own_terrain_span_buff_point_state
bool forward_enemy_terrain_span_buff_point_state
bool behind_enemy_terrain_span_buff_point_state
bool below_central_own_terrain_span_buff_point_state
bool upper_central_own_terrain_span_buff_point_state
bool below_central_enemy_terrain_span_buff_point_state
bool upper_central_enemy_terrain_span_buff_point_state
bool below_road_own_terrain_span_buff_point_state
bool upper_road_own_terrain_span_buff_point_state
bool below_road_enemy_terrain_span_buff_point_state
bool upper_road_enemy_terrain_span_buff_point_state
bool own_fort_buff_point
bool own_outpost_buff_point
bool nan_overlapping_supplier_zone
bool overlapping_supplier_zone
bool own_large_resource_island_point
bool enemy_large_resource_island_point
bool central_buff_point
bool enemy_fortress_buff_point

time stamp
"""
  __slots__ = ['base_buff_point_state','own_central_elevated_ground_state','enemy_central_elevated_ground_state','own_trapezoidal_elevated_ground_state','enemy_trapezoidal_elevated_ground_state','forward_own_terrain_span_buff_point_state','behind_own_terrain_span_buff_point_state','forward_enemy_terrain_span_buff_point_state','behind_enemy_terrain_span_buff_point_state','below_central_own_terrain_span_buff_point_state','upper_central_own_terrain_span_buff_point_state','below_central_enemy_terrain_span_buff_point_state','upper_central_enemy_terrain_span_buff_point_state','below_road_own_terrain_span_buff_point_state','upper_road_own_terrain_span_buff_point_state','below_road_enemy_terrain_span_buff_point_state','upper_road_enemy_terrain_span_buff_point_state','own_fort_buff_point','own_outpost_buff_point','nan_overlapping_supplier_zone','overlapping_supplier_zone','own_large_resource_island_point','enemy_large_resource_island_point','central_buff_point','enemy_fortress_buff_point','stamp']
  _slot_types = ['bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base_buff_point_state,own_central_elevated_ground_state,enemy_central_elevated_ground_state,own_trapezoidal_elevated_ground_state,enemy_trapezoidal_elevated_ground_state,forward_own_terrain_span_buff_point_state,behind_own_terrain_span_buff_point_state,forward_enemy_terrain_span_buff_point_state,behind_enemy_terrain_span_buff_point_state,below_central_own_terrain_span_buff_point_state,upper_central_own_terrain_span_buff_point_state,below_central_enemy_terrain_span_buff_point_state,upper_central_enemy_terrain_span_buff_point_state,below_road_own_terrain_span_buff_point_state,upper_road_own_terrain_span_buff_point_state,below_road_enemy_terrain_span_buff_point_state,upper_road_enemy_terrain_span_buff_point_state,own_fort_buff_point,own_outpost_buff_point,nan_overlapping_supplier_zone,overlapping_supplier_zone,own_large_resource_island_point,enemy_large_resource_island_point,central_buff_point,enemy_fortress_buff_point,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RfidStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.base_buff_point_state is None:
        self.base_buff_point_state = False
      if self.own_central_elevated_ground_state is None:
        self.own_central_elevated_ground_state = False
      if self.enemy_central_elevated_ground_state is None:
        self.enemy_central_elevated_ground_state = False
      if self.own_trapezoidal_elevated_ground_state is None:
        self.own_trapezoidal_elevated_ground_state = False
      if self.enemy_trapezoidal_elevated_ground_state is None:
        self.enemy_trapezoidal_elevated_ground_state = False
      if self.forward_own_terrain_span_buff_point_state is None:
        self.forward_own_terrain_span_buff_point_state = False
      if self.behind_own_terrain_span_buff_point_state is None:
        self.behind_own_terrain_span_buff_point_state = False
      if self.forward_enemy_terrain_span_buff_point_state is None:
        self.forward_enemy_terrain_span_buff_point_state = False
      if self.behind_enemy_terrain_span_buff_point_state is None:
        self.behind_enemy_terrain_span_buff_point_state = False
      if self.below_central_own_terrain_span_buff_point_state is None:
        self.below_central_own_terrain_span_buff_point_state = False
      if self.upper_central_own_terrain_span_buff_point_state is None:
        self.upper_central_own_terrain_span_buff_point_state = False
      if self.below_central_enemy_terrain_span_buff_point_state is None:
        self.below_central_enemy_terrain_span_buff_point_state = False
      if self.upper_central_enemy_terrain_span_buff_point_state is None:
        self.upper_central_enemy_terrain_span_buff_point_state = False
      if self.below_road_own_terrain_span_buff_point_state is None:
        self.below_road_own_terrain_span_buff_point_state = False
      if self.upper_road_own_terrain_span_buff_point_state is None:
        self.upper_road_own_terrain_span_buff_point_state = False
      if self.below_road_enemy_terrain_span_buff_point_state is None:
        self.below_road_enemy_terrain_span_buff_point_state = False
      if self.upper_road_enemy_terrain_span_buff_point_state is None:
        self.upper_road_enemy_terrain_span_buff_point_state = False
      if self.own_fort_buff_point is None:
        self.own_fort_buff_point = False
      if self.own_outpost_buff_point is None:
        self.own_outpost_buff_point = False
      if self.nan_overlapping_supplier_zone is None:
        self.nan_overlapping_supplier_zone = False
      if self.overlapping_supplier_zone is None:
        self.overlapping_supplier_zone = False
      if self.own_large_resource_island_point is None:
        self.own_large_resource_island_point = False
      if self.enemy_large_resource_island_point is None:
        self.enemy_large_resource_island_point = False
      if self.central_buff_point is None:
        self.central_buff_point = False
      if self.enemy_fortress_buff_point is None:
        self.enemy_fortress_buff_point = False
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.base_buff_point_state = False
      self.own_central_elevated_ground_state = False
      self.enemy_central_elevated_ground_state = False
      self.own_trapezoidal_elevated_ground_state = False
      self.enemy_trapezoidal_elevated_ground_state = False
      self.forward_own_terrain_span_buff_point_state = False
      self.behind_own_terrain_span_buff_point_state = False
      self.forward_enemy_terrain_span_buff_point_state = False
      self.behind_enemy_terrain_span_buff_point_state = False
      self.below_central_own_terrain_span_buff_point_state = False
      self.upper_central_own_terrain_span_buff_point_state = False
      self.below_central_enemy_terrain_span_buff_point_state = False
      self.upper_central_enemy_terrain_span_buff_point_state = False
      self.below_road_own_terrain_span_buff_point_state = False
      self.upper_road_own_terrain_span_buff_point_state = False
      self.below_road_enemy_terrain_span_buff_point_state = False
      self.upper_road_enemy_terrain_span_buff_point_state = False
      self.own_fort_buff_point = False
      self.own_outpost_buff_point = False
      self.nan_overlapping_supplier_zone = False
      self.overlapping_supplier_zone = False
      self.own_large_resource_island_point = False
      self.enemy_large_resource_island_point = False
      self.central_buff_point = False
      self.enemy_fortress_buff_point = False
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_25B2I().pack(_x.base_buff_point_state, _x.own_central_elevated_ground_state, _x.enemy_central_elevated_ground_state, _x.own_trapezoidal_elevated_ground_state, _x.enemy_trapezoidal_elevated_ground_state, _x.forward_own_terrain_span_buff_point_state, _x.behind_own_terrain_span_buff_point_state, _x.forward_enemy_terrain_span_buff_point_state, _x.behind_enemy_terrain_span_buff_point_state, _x.below_central_own_terrain_span_buff_point_state, _x.upper_central_own_terrain_span_buff_point_state, _x.below_central_enemy_terrain_span_buff_point_state, _x.upper_central_enemy_terrain_span_buff_point_state, _x.below_road_own_terrain_span_buff_point_state, _x.upper_road_own_terrain_span_buff_point_state, _x.below_road_enemy_terrain_span_buff_point_state, _x.upper_road_enemy_terrain_span_buff_point_state, _x.own_fort_buff_point, _x.own_outpost_buff_point, _x.nan_overlapping_supplier_zone, _x.overlapping_supplier_zone, _x.own_large_resource_island_point, _x.enemy_large_resource_island_point, _x.central_buff_point, _x.enemy_fortress_buff_point, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.base_buff_point_state, _x.own_central_elevated_ground_state, _x.enemy_central_elevated_ground_state, _x.own_trapezoidal_elevated_ground_state, _x.enemy_trapezoidal_elevated_ground_state, _x.forward_own_terrain_span_buff_point_state, _x.behind_own_terrain_span_buff_point_state, _x.forward_enemy_terrain_span_buff_point_state, _x.behind_enemy_terrain_span_buff_point_state, _x.below_central_own_terrain_span_buff_point_state, _x.upper_central_own_terrain_span_buff_point_state, _x.below_central_enemy_terrain_span_buff_point_state, _x.upper_central_enemy_terrain_span_buff_point_state, _x.below_road_own_terrain_span_buff_point_state, _x.upper_road_own_terrain_span_buff_point_state, _x.below_road_enemy_terrain_span_buff_point_state, _x.upper_road_enemy_terrain_span_buff_point_state, _x.own_fort_buff_point, _x.own_outpost_buff_point, _x.nan_overlapping_supplier_zone, _x.overlapping_supplier_zone, _x.own_large_resource_island_point, _x.enemy_large_resource_island_point, _x.central_buff_point, _x.enemy_fortress_buff_point, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_25B2I().unpack(str[start:end])
      self.base_buff_point_state = bool(self.base_buff_point_state)
      self.own_central_elevated_ground_state = bool(self.own_central_elevated_ground_state)
      self.enemy_central_elevated_ground_state = bool(self.enemy_central_elevated_ground_state)
      self.own_trapezoidal_elevated_ground_state = bool(self.own_trapezoidal_elevated_ground_state)
      self.enemy_trapezoidal_elevated_ground_state = bool(self.enemy_trapezoidal_elevated_ground_state)
      self.forward_own_terrain_span_buff_point_state = bool(self.forward_own_terrain_span_buff_point_state)
      self.behind_own_terrain_span_buff_point_state = bool(self.behind_own_terrain_span_buff_point_state)
      self.forward_enemy_terrain_span_buff_point_state = bool(self.forward_enemy_terrain_span_buff_point_state)
      self.behind_enemy_terrain_span_buff_point_state = bool(self.behind_enemy_terrain_span_buff_point_state)
      self.below_central_own_terrain_span_buff_point_state = bool(self.below_central_own_terrain_span_buff_point_state)
      self.upper_central_own_terrain_span_buff_point_state = bool(self.upper_central_own_terrain_span_buff_point_state)
      self.below_central_enemy_terrain_span_buff_point_state = bool(self.below_central_enemy_terrain_span_buff_point_state)
      self.upper_central_enemy_terrain_span_buff_point_state = bool(self.upper_central_enemy_terrain_span_buff_point_state)
      self.below_road_own_terrain_span_buff_point_state = bool(self.below_road_own_terrain_span_buff_point_state)
      self.upper_road_own_terrain_span_buff_point_state = bool(self.upper_road_own_terrain_span_buff_point_state)
      self.below_road_enemy_terrain_span_buff_point_state = bool(self.below_road_enemy_terrain_span_buff_point_state)
      self.upper_road_enemy_terrain_span_buff_point_state = bool(self.upper_road_enemy_terrain_span_buff_point_state)
      self.own_fort_buff_point = bool(self.own_fort_buff_point)
      self.own_outpost_buff_point = bool(self.own_outpost_buff_point)
      self.nan_overlapping_supplier_zone = bool(self.nan_overlapping_supplier_zone)
      self.overlapping_supplier_zone = bool(self.overlapping_supplier_zone)
      self.own_large_resource_island_point = bool(self.own_large_resource_island_point)
      self.enemy_large_resource_island_point = bool(self.enemy_large_resource_island_point)
      self.central_buff_point = bool(self.central_buff_point)
      self.enemy_fortress_buff_point = bool(self.enemy_fortress_buff_point)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_25B2I().pack(_x.base_buff_point_state, _x.own_central_elevated_ground_state, _x.enemy_central_elevated_ground_state, _x.own_trapezoidal_elevated_ground_state, _x.enemy_trapezoidal_elevated_ground_state, _x.forward_own_terrain_span_buff_point_state, _x.behind_own_terrain_span_buff_point_state, _x.forward_enemy_terrain_span_buff_point_state, _x.behind_enemy_terrain_span_buff_point_state, _x.below_central_own_terrain_span_buff_point_state, _x.upper_central_own_terrain_span_buff_point_state, _x.below_central_enemy_terrain_span_buff_point_state, _x.upper_central_enemy_terrain_span_buff_point_state, _x.below_road_own_terrain_span_buff_point_state, _x.upper_road_own_terrain_span_buff_point_state, _x.below_road_enemy_terrain_span_buff_point_state, _x.upper_road_enemy_terrain_span_buff_point_state, _x.own_fort_buff_point, _x.own_outpost_buff_point, _x.nan_overlapping_supplier_zone, _x.overlapping_supplier_zone, _x.own_large_resource_island_point, _x.enemy_large_resource_island_point, _x.central_buff_point, _x.enemy_fortress_buff_point, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.base_buff_point_state, _x.own_central_elevated_ground_state, _x.enemy_central_elevated_ground_state, _x.own_trapezoidal_elevated_ground_state, _x.enemy_trapezoidal_elevated_ground_state, _x.forward_own_terrain_span_buff_point_state, _x.behind_own_terrain_span_buff_point_state, _x.forward_enemy_terrain_span_buff_point_state, _x.behind_enemy_terrain_span_buff_point_state, _x.below_central_own_terrain_span_buff_point_state, _x.upper_central_own_terrain_span_buff_point_state, _x.below_central_enemy_terrain_span_buff_point_state, _x.upper_central_enemy_terrain_span_buff_point_state, _x.below_road_own_terrain_span_buff_point_state, _x.upper_road_own_terrain_span_buff_point_state, _x.below_road_enemy_terrain_span_buff_point_state, _x.upper_road_enemy_terrain_span_buff_point_state, _x.own_fort_buff_point, _x.own_outpost_buff_point, _x.nan_overlapping_supplier_zone, _x.overlapping_supplier_zone, _x.own_large_resource_island_point, _x.enemy_large_resource_island_point, _x.central_buff_point, _x.enemy_fortress_buff_point, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_25B2I().unpack(str[start:end])
      self.base_buff_point_state = bool(self.base_buff_point_state)
      self.own_central_elevated_ground_state = bool(self.own_central_elevated_ground_state)
      self.enemy_central_elevated_ground_state = bool(self.enemy_central_elevated_ground_state)
      self.own_trapezoidal_elevated_ground_state = bool(self.own_trapezoidal_elevated_ground_state)
      self.enemy_trapezoidal_elevated_ground_state = bool(self.enemy_trapezoidal_elevated_ground_state)
      self.forward_own_terrain_span_buff_point_state = bool(self.forward_own_terrain_span_buff_point_state)
      self.behind_own_terrain_span_buff_point_state = bool(self.behind_own_terrain_span_buff_point_state)
      self.forward_enemy_terrain_span_buff_point_state = bool(self.forward_enemy_terrain_span_buff_point_state)
      self.behind_enemy_terrain_span_buff_point_state = bool(self.behind_enemy_terrain_span_buff_point_state)
      self.below_central_own_terrain_span_buff_point_state = bool(self.below_central_own_terrain_span_buff_point_state)
      self.upper_central_own_terrain_span_buff_point_state = bool(self.upper_central_own_terrain_span_buff_point_state)
      self.below_central_enemy_terrain_span_buff_point_state = bool(self.below_central_enemy_terrain_span_buff_point_state)
      self.upper_central_enemy_terrain_span_buff_point_state = bool(self.upper_central_enemy_terrain_span_buff_point_state)
      self.below_road_own_terrain_span_buff_point_state = bool(self.below_road_own_terrain_span_buff_point_state)
      self.upper_road_own_terrain_span_buff_point_state = bool(self.upper_road_own_terrain_span_buff_point_state)
      self.below_road_enemy_terrain_span_buff_point_state = bool(self.below_road_enemy_terrain_span_buff_point_state)
      self.upper_road_enemy_terrain_span_buff_point_state = bool(self.upper_road_enemy_terrain_span_buff_point_state)
      self.own_fort_buff_point = bool(self.own_fort_buff_point)
      self.own_outpost_buff_point = bool(self.own_outpost_buff_point)
      self.nan_overlapping_supplier_zone = bool(self.nan_overlapping_supplier_zone)
      self.overlapping_supplier_zone = bool(self.overlapping_supplier_zone)
      self.own_large_resource_island_point = bool(self.own_large_resource_island_point)
      self.enemy_large_resource_island_point = bool(self.enemy_large_resource_island_point)
      self.central_buff_point = bool(self.central_buff_point)
      self.enemy_fortress_buff_point = bool(self.enemy_fortress_buff_point)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_25B2I = None
def _get_struct_25B2I():
    global _struct_25B2I
    if _struct_25B2I is None:
        _struct_25B2I = struct.Struct("<25B2I")
    return _struct_25B2I
