# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/VTReceiverControlData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VTReceiverControlData(genpy.Message):
  _md5sum = "ccb3d14b76ed93d4c7a7597427ff5b6f"
  _type = "rm_msgs/VTReceiverControlData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 joystick_r_x
float64 joystick_r_y
float64 joystick_l_y
float64 joystick_l_x

uint8 mode_switch
uint8 MODE_C = 0
uint8 MODE_N = 1
uint8 MODE_S = 2

bool pause_button
bool custom_button_l
bool custom_button_r
float64 wheel
bool trigger

int16 mouse_x
int16 mouse_y
int16 mouse_wheel
bool mouse_left_down
bool mouse_right_down
bool mouse_mid_down

bool key_w
bool key_s
bool key_a
bool key_d
bool key_shift
bool key_ctrl
bool key_q
bool key_e
bool key_r
bool key_f
bool key_g
bool key_z
bool key_x
bool key_c
bool key_v
bool key_b
"""
  # Pseudo-constants
  MODE_C = 0
  MODE_N = 1
  MODE_S = 2

  __slots__ = ['joystick_r_x','joystick_r_y','joystick_l_y','joystick_l_x','mode_switch','pause_button','custom_button_l','custom_button_r','wheel','trigger','mouse_x','mouse_y','mouse_wheel','mouse_left_down','mouse_right_down','mouse_mid_down','key_w','key_s','key_a','key_d','key_shift','key_ctrl','key_q','key_e','key_r','key_f','key_g','key_z','key_x','key_c','key_v','key_b']
  _slot_types = ['float64','float64','float64','float64','uint8','bool','bool','bool','float64','bool','int16','int16','int16','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joystick_r_x,joystick_r_y,joystick_l_y,joystick_l_x,mode_switch,pause_button,custom_button_l,custom_button_r,wheel,trigger,mouse_x,mouse_y,mouse_wheel,mouse_left_down,mouse_right_down,mouse_mid_down,key_w,key_s,key_a,key_d,key_shift,key_ctrl,key_q,key_e,key_r,key_f,key_g,key_z,key_x,key_c,key_v,key_b

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VTReceiverControlData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joystick_r_x is None:
        self.joystick_r_x = 0.
      if self.joystick_r_y is None:
        self.joystick_r_y = 0.
      if self.joystick_l_y is None:
        self.joystick_l_y = 0.
      if self.joystick_l_x is None:
        self.joystick_l_x = 0.
      if self.mode_switch is None:
        self.mode_switch = 0
      if self.pause_button is None:
        self.pause_button = False
      if self.custom_button_l is None:
        self.custom_button_l = False
      if self.custom_button_r is None:
        self.custom_button_r = False
      if self.wheel is None:
        self.wheel = 0.
      if self.trigger is None:
        self.trigger = False
      if self.mouse_x is None:
        self.mouse_x = 0
      if self.mouse_y is None:
        self.mouse_y = 0
      if self.mouse_wheel is None:
        self.mouse_wheel = 0
      if self.mouse_left_down is None:
        self.mouse_left_down = False
      if self.mouse_right_down is None:
        self.mouse_right_down = False
      if self.mouse_mid_down is None:
        self.mouse_mid_down = False
      if self.key_w is None:
        self.key_w = False
      if self.key_s is None:
        self.key_s = False
      if self.key_a is None:
        self.key_a = False
      if self.key_d is None:
        self.key_d = False
      if self.key_shift is None:
        self.key_shift = False
      if self.key_ctrl is None:
        self.key_ctrl = False
      if self.key_q is None:
        self.key_q = False
      if self.key_e is None:
        self.key_e = False
      if self.key_r is None:
        self.key_r = False
      if self.key_f is None:
        self.key_f = False
      if self.key_g is None:
        self.key_g = False
      if self.key_z is None:
        self.key_z = False
      if self.key_x is None:
        self.key_x = False
      if self.key_c is None:
        self.key_c = False
      if self.key_v is None:
        self.key_v = False
      if self.key_b is None:
        self.key_b = False
    else:
      self.joystick_r_x = 0.
      self.joystick_r_y = 0.
      self.joystick_l_y = 0.
      self.joystick_l_x = 0.
      self.mode_switch = 0
      self.pause_button = False
      self.custom_button_l = False
      self.custom_button_r = False
      self.wheel = 0.
      self.trigger = False
      self.mouse_x = 0
      self.mouse_y = 0
      self.mouse_wheel = 0
      self.mouse_left_down = False
      self.mouse_right_down = False
      self.mouse_mid_down = False
      self.key_w = False
      self.key_s = False
      self.key_a = False
      self.key_d = False
      self.key_shift = False
      self.key_ctrl = False
      self.key_q = False
      self.key_e = False
      self.key_r = False
      self.key_f = False
      self.key_g = False
      self.key_z = False
      self.key_x = False
      self.key_c = False
      self.key_v = False
      self.key_b = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d4BdB3h19B().pack(_x.joystick_r_x, _x.joystick_r_y, _x.joystick_l_y, _x.joystick_l_x, _x.mode_switch, _x.pause_button, _x.custom_button_l, _x.custom_button_r, _x.wheel, _x.trigger, _x.mouse_x, _x.mouse_y, _x.mouse_wheel, _x.mouse_left_down, _x.mouse_right_down, _x.mouse_mid_down, _x.key_w, _x.key_s, _x.key_a, _x.key_d, _x.key_shift, _x.key_ctrl, _x.key_q, _x.key_e, _x.key_r, _x.key_f, _x.key_g, _x.key_z, _x.key_x, _x.key_c, _x.key_v, _x.key_b))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 70
      (_x.joystick_r_x, _x.joystick_r_y, _x.joystick_l_y, _x.joystick_l_x, _x.mode_switch, _x.pause_button, _x.custom_button_l, _x.custom_button_r, _x.wheel, _x.trigger, _x.mouse_x, _x.mouse_y, _x.mouse_wheel, _x.mouse_left_down, _x.mouse_right_down, _x.mouse_mid_down, _x.key_w, _x.key_s, _x.key_a, _x.key_d, _x.key_shift, _x.key_ctrl, _x.key_q, _x.key_e, _x.key_r, _x.key_f, _x.key_g, _x.key_z, _x.key_x, _x.key_c, _x.key_v, _x.key_b,) = _get_struct_4d4BdB3h19B().unpack(str[start:end])
      self.pause_button = bool(self.pause_button)
      self.custom_button_l = bool(self.custom_button_l)
      self.custom_button_r = bool(self.custom_button_r)
      self.trigger = bool(self.trigger)
      self.mouse_left_down = bool(self.mouse_left_down)
      self.mouse_right_down = bool(self.mouse_right_down)
      self.mouse_mid_down = bool(self.mouse_mid_down)
      self.key_w = bool(self.key_w)
      self.key_s = bool(self.key_s)
      self.key_a = bool(self.key_a)
      self.key_d = bool(self.key_d)
      self.key_shift = bool(self.key_shift)
      self.key_ctrl = bool(self.key_ctrl)
      self.key_q = bool(self.key_q)
      self.key_e = bool(self.key_e)
      self.key_r = bool(self.key_r)
      self.key_f = bool(self.key_f)
      self.key_g = bool(self.key_g)
      self.key_z = bool(self.key_z)
      self.key_x = bool(self.key_x)
      self.key_c = bool(self.key_c)
      self.key_v = bool(self.key_v)
      self.key_b = bool(self.key_b)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d4BdB3h19B().pack(_x.joystick_r_x, _x.joystick_r_y, _x.joystick_l_y, _x.joystick_l_x, _x.mode_switch, _x.pause_button, _x.custom_button_l, _x.custom_button_r, _x.wheel, _x.trigger, _x.mouse_x, _x.mouse_y, _x.mouse_wheel, _x.mouse_left_down, _x.mouse_right_down, _x.mouse_mid_down, _x.key_w, _x.key_s, _x.key_a, _x.key_d, _x.key_shift, _x.key_ctrl, _x.key_q, _x.key_e, _x.key_r, _x.key_f, _x.key_g, _x.key_z, _x.key_x, _x.key_c, _x.key_v, _x.key_b))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 70
      (_x.joystick_r_x, _x.joystick_r_y, _x.joystick_l_y, _x.joystick_l_x, _x.mode_switch, _x.pause_button, _x.custom_button_l, _x.custom_button_r, _x.wheel, _x.trigger, _x.mouse_x, _x.mouse_y, _x.mouse_wheel, _x.mouse_left_down, _x.mouse_right_down, _x.mouse_mid_down, _x.key_w, _x.key_s, _x.key_a, _x.key_d, _x.key_shift, _x.key_ctrl, _x.key_q, _x.key_e, _x.key_r, _x.key_f, _x.key_g, _x.key_z, _x.key_x, _x.key_c, _x.key_v, _x.key_b,) = _get_struct_4d4BdB3h19B().unpack(str[start:end])
      self.pause_button = bool(self.pause_button)
      self.custom_button_l = bool(self.custom_button_l)
      self.custom_button_r = bool(self.custom_button_r)
      self.trigger = bool(self.trigger)
      self.mouse_left_down = bool(self.mouse_left_down)
      self.mouse_right_down = bool(self.mouse_right_down)
      self.mouse_mid_down = bool(self.mouse_mid_down)
      self.key_w = bool(self.key_w)
      self.key_s = bool(self.key_s)
      self.key_a = bool(self.key_a)
      self.key_d = bool(self.key_d)
      self.key_shift = bool(self.key_shift)
      self.key_ctrl = bool(self.key_ctrl)
      self.key_q = bool(self.key_q)
      self.key_e = bool(self.key_e)
      self.key_r = bool(self.key_r)
      self.key_f = bool(self.key_f)
      self.key_g = bool(self.key_g)
      self.key_z = bool(self.key_z)
      self.key_x = bool(self.key_x)
      self.key_c = bool(self.key_c)
      self.key_v = bool(self.key_v)
      self.key_b = bool(self.key_b)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d4BdB3h19B = None
def _get_struct_4d4BdB3h19B():
    global _struct_4d4BdB3h19B
    if _struct_4d4BdB3h19B is None:
        _struct_4d4BdB3h19B = struct.Struct("<4d4BdB3h19B")
    return _struct_4d4BdB3h19B
