(cl:in-package rm_msgs-msg)
(cl:export '(HERO_POSITION_X-VAL
          HERO_POSITION_X
          HERO_POSITION_Y-VAL
          HERO_POSITION_Y
          ENGINEER_POSITION_X-VAL
          ENGINEER_POSITION_X
          ENGINEER_POSITION_Y-VAL
          ENGINEER_POSITION_Y
          INFANTRY_3_POSITION_X-VAL
          INFANTRY_3_POSITION_X
          INFANTRY_3_POSITION_Y-VAL
          INFANTRY_3_POSITION_Y
          INFANTRY_4_POSITION_X-VAL
          INFANTRY_4_POSITION_X
          INFANTRY_4_POSITION_Y-VAL
          INFANTRY_4_POSITION_Y
          INFANTRY_5_POSITION_X-VAL
          INFANTRY_5_POSITION_X
          INFANTRY_5_POSITION_Y-VAL
          INFANTRY_5_POSITION_Y
          SENTRY_POSITION_X-VAL
          SENTRY_POSITION_X
          SENTRY_POSITION_Y-VAL
          SENTRY_POSITION_Y
          STAMP-VAL
          STAMP
))