(cl:in-package rm_msgs-msg)
(cl:export '(JOYSTICK_R_X-VAL
          JOYSTICK_R_X
          JOYSTICK_R_Y-VAL
          JOYSTICK_R_Y
          JOYSTICK_L_Y-VAL
          JOYSTICK_L_Y
          JOYSTICK_L_X-VAL
          JOYSTICK_L_X
          MODE_SWITCH-VAL
          MODE_SWITCH
          PAUSE_BUTTON-VAL
          PAUSE_BUTTON
          CUSTOM_BUTTON_L-VAL
          CUSTOM_BUTTON_L
          CUSTOM_BUTTON_R-VAL
          CUSTOM_BUTTON_R
          WHEEL-VAL
          WHEEL
          TRIGGER-VAL
          TRIGGER
          MOUSE_X-VAL
          MOUSE_X
          MOUSE_Y-VAL
          MOUSE_Y
          MOUSE_WHEEL-VAL
          MOUSE_WHEEL
          MOUSE_LEFT_DOWN-VAL
          MOUSE_LEFT_DOWN
          MOUSE_RIGHT_DOWN-VAL
          MOUSE_RIGHT_DOWN
          MOUSE_MID_DOWN-VAL
          MOUSE_MID_DOWN
          KEY_W-VAL
          KEY_W
          KEY_S-VAL
          KEY_S
          KEY_A-VAL
          KEY_A
          KEY_D-VAL
          KEY_D
          KEY_SHIFT-VAL
          KEY_SHIFT
          KEY_CTRL-VAL
          KEY_CTRL
          KEY_Q-VAL
          KEY_Q
          KEY_E-VAL
          KEY_E
          KEY_R-VAL
          KEY_R
          KEY_F-VAL
          KEY_F
          KEY_G-VAL
          KEY_G
          KEY_Z-VAL
          KEY_Z
          KEY_X-VAL
          KEY_X
          KEY_C-VAL
          KEY_C
          KEY_V-VAL
          KEY_V
          KEY_B-VAL
          KEY_B
))