(cl:in-package rm_msgs-msg)
(cl:export '(MOUSE_X-VAL
          MOUSE_X
          MOUSE_Y-VAL
          MOUSE_Y
          MOUSE_Z-VAL
          MOUSE_Z
          LEFT_BUTTON_DOWN-VAL
          LEFT_BUTTON_DOWN
          RIGHT_BUTTON_DOWN-VAL
          RIGHT_BUTTON_DOWN
          KEY_W-VAL
          KEY_W
          KEY_S-VAL
          KEY_S
          KEY_A-VAL
          KEY_A
          KEY_D-VAL
          KEY_D
          KEY_SHIFT-VAL
          KEY_SHIFT
          KEY_CTRL-VAL
          KEY_CTRL
          KEY_Q-VAL
          KEY_Q
          KEY_E-VAL
          KEY_E
          KEY_R-VAL
          KEY_R
          KEY_F-VAL
          KEY_F
          KEY_G-VAL
          KEY_G
          KEY_Z-VAL
          KEY_Z
          KEY_X-VAL
          KEY_X
          KEY_C-VAL
          KEY_C
          KEY_V-VAL
          KEY_V
          KEY_B-VAL
          KEY_B
))