// Generated by gencpp from file sentry_chassis_controller/ChassisState.msg
// DO NOT EDIT!


#ifndef SENTRY_CHASSIS_CONTROLLER_MESSAGE_CHASSISSTATE_H
#define SENTRY_CHASSIS_CONTROLLER_MESSAGE_CHASSISSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sentry_chassis_controller
{
template <class ContainerAllocator>
struct ChassisState_
{
  typedef ChassisState_<ContainerAllocator> Type;

  ChassisState_()
    : header()
    , cmd_vx(0.0)
    , cmd_vy(0.0)
    , cmd_wz(0.0)
    , desired_wheel_speeds()
    , actual_wheel_speeds()
    , desired_steering_angles()
    , actual_steering_angles()
    , wheel_efforts()
    , steering_efforts()
    , cmd_vel_active(false)  {
      desired_wheel_speeds.assign(0.0);

      actual_wheel_speeds.assign(0.0);

      desired_steering_angles.assign(0.0);

      actual_steering_angles.assign(0.0);

      wheel_efforts.assign(0.0);

      steering_efforts.assign(0.0);
  }
  ChassisState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd_vx(0.0)
    , cmd_vy(0.0)
    , cmd_wz(0.0)
    , desired_wheel_speeds()
    , actual_wheel_speeds()
    , desired_steering_angles()
    , actual_steering_angles()
    , wheel_efforts()
    , steering_efforts()
    , cmd_vel_active(false)  {
  (void)_alloc;
      desired_wheel_speeds.assign(0.0);

      actual_wheel_speeds.assign(0.0);

      desired_steering_angles.assign(0.0);

      actual_steering_angles.assign(0.0);

      wheel_efforts.assign(0.0);

      steering_efforts.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _cmd_vx_type;
  _cmd_vx_type cmd_vx;

   typedef double _cmd_vy_type;
  _cmd_vy_type cmd_vy;

   typedef double _cmd_wz_type;
  _cmd_wz_type cmd_wz;

   typedef boost::array<double, 4>  _desired_wheel_speeds_type;
  _desired_wheel_speeds_type desired_wheel_speeds;

   typedef boost::array<double, 4>  _actual_wheel_speeds_type;
  _actual_wheel_speeds_type actual_wheel_speeds;

   typedef boost::array<double, 4>  _desired_steering_angles_type;
  _desired_steering_angles_type desired_steering_angles;

   typedef boost::array<double, 4>  _actual_steering_angles_type;
  _actual_steering_angles_type actual_steering_angles;

   typedef boost::array<double, 4>  _wheel_efforts_type;
  _wheel_efforts_type wheel_efforts;

   typedef boost::array<double, 4>  _steering_efforts_type;
  _steering_efforts_type steering_efforts;

   typedef uint8_t _cmd_vel_active_type;
  _cmd_vel_active_type cmd_vel_active;





  typedef boost::shared_ptr< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> const> ConstPtr;

}; // struct ChassisState_

typedef ::sentry_chassis_controller::ChassisState_<std::allocator<void> > ChassisState;

typedef boost::shared_ptr< ::sentry_chassis_controller::ChassisState > ChassisStatePtr;
typedef boost::shared_ptr< ::sentry_chassis_controller::ChassisState const> ChassisStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentry_chassis_controller::ChassisState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentry_chassis_controller::ChassisState_<ContainerAllocator1> & lhs, const ::sentry_chassis_controller::ChassisState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cmd_vx == rhs.cmd_vx &&
    lhs.cmd_vy == rhs.cmd_vy &&
    lhs.cmd_wz == rhs.cmd_wz &&
    lhs.desired_wheel_speeds == rhs.desired_wheel_speeds &&
    lhs.actual_wheel_speeds == rhs.actual_wheel_speeds &&
    lhs.desired_steering_angles == rhs.desired_steering_angles &&
    lhs.actual_steering_angles == rhs.actual_steering_angles &&
    lhs.wheel_efforts == rhs.wheel_efforts &&
    lhs.steering_efforts == rhs.steering_efforts &&
    lhs.cmd_vel_active == rhs.cmd_vel_active;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentry_chassis_controller::ChassisState_<ContainerAllocator1> & lhs, const ::sentry_chassis_controller::ChassisState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentry_chassis_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be09b6eddd3e724282cde2412802ba78";
  }

  static const char* value(const ::sentry_chassis_controller::ChassisState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe09b6eddd3e7242ULL;
  static const uint64_t static_value2 = 0x82cde2412802ba78ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentry_chassis_controller/ChassisState";
  }

  static const char* value(const ::sentry_chassis_controller::ChassisState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 底盘状态消息\n"
"Header header\n"
"\n"
"# 指令速度\n"
"float64 cmd_vx\n"
"float64 cmd_vy\n"
"float64 cmd_wz\n"
"\n"
"# 轮子期望转速 (rad/s)\n"
"float64[4] desired_wheel_speeds\n"
"# 轮子实际转速 (rad/s)\n"
"float64[4] actual_wheel_speeds\n"
"\n"
"# 轮子期望转向角度 (rad)\n"
"float64[4] desired_steering_angles\n"
"# 轮子实际转向角度 (rad)\n"
"float64[4] actual_steering_angles\n"
"\n"
"# 轮子控制力矩\n"
"float64[4] wheel_efforts\n"
"# 转向控制力矩\n"
"float64[4] steering_efforts\n"
"\n"
"# 是否接收到有效指令\n"
"bool cmd_vel_active\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sentry_chassis_controller::ChassisState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd_vx);
      stream.next(m.cmd_vy);
      stream.next(m.cmd_wz);
      stream.next(m.desired_wheel_speeds);
      stream.next(m.actual_wheel_speeds);
      stream.next(m.desired_steering_angles);
      stream.next(m.actual_steering_angles);
      stream.next(m.wheel_efforts);
      stream.next(m.steering_efforts);
      stream.next(m.cmd_vel_active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChassisState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentry_chassis_controller::ChassisState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentry_chassis_controller::ChassisState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_vx: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_vx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_vy: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_vy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_wz: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_wz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "desired_wheel_speeds: ";
    if (v.desired_wheel_speeds.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.desired_wheel_speeds.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.desired_wheel_speeds[i]);
    }
    if (v.desired_wheel_speeds.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actual_wheel_speeds: ";
    if (v.actual_wheel_speeds.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.actual_wheel_speeds.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.actual_wheel_speeds[i]);
    }
    if (v.actual_wheel_speeds.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "desired_steering_angles: ";
    if (v.desired_steering_angles.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.desired_steering_angles.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.desired_steering_angles[i]);
    }
    if (v.desired_steering_angles.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actual_steering_angles: ";
    if (v.actual_steering_angles.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.actual_steering_angles.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.actual_steering_angles[i]);
    }
    if (v.actual_steering_angles.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_efforts: ";
    if (v.wheel_efforts.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_efforts.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.wheel_efforts[i]);
    }
    if (v.wheel_efforts.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_efforts: ";
    if (v.steering_efforts.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.steering_efforts.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.steering_efforts[i]);
    }
    if (v.steering_efforts.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_vel_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_vel_active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTRY_CHASSIS_CONTROLLER_MESSAGE_CHASSISSTATE_H
