// Generated by gencpp from file sentry_chassis_controller/WheelState.msg
// DO NOT EDIT!


#ifndef SENTRY_CHASSIS_CONTROLLER_MESSAGE_WHEELSTATE_H
#define SENTRY_CHASSIS_CONTROLLER_MESSAGE_WHEELSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sentry_chassis_controller
{
template <class ContainerAllocator>
struct WheelState_
{
  typedef WheelState_<ContainerAllocator> Type;

  WheelState_()
    : header()
    , steering_angle()
    , wheel_speed()
    , wheel_velocity()
    , wheel_torque()
    , wheel_current()  {
      steering_angle.assign(0.0);

      wheel_speed.assign(0.0);

      wheel_velocity.assign(0.0);

      wheel_torque.assign(0.0);

      wheel_current.assign(0.0);
  }
  WheelState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering_angle()
    , wheel_speed()
    , wheel_velocity()
    , wheel_torque()
    , wheel_current()  {
  (void)_alloc;
      steering_angle.assign(0.0);

      wheel_speed.assign(0.0);

      wheel_velocity.assign(0.0);

      wheel_torque.assign(0.0);

      wheel_current.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 4>  _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef boost::array<double, 4>  _wheel_speed_type;
  _wheel_speed_type wheel_speed;

   typedef boost::array<double, 4>  _wheel_velocity_type;
  _wheel_velocity_type wheel_velocity;

   typedef boost::array<double, 4>  _wheel_torque_type;
  _wheel_torque_type wheel_torque;

   typedef boost::array<double, 4>  _wheel_current_type;
  _wheel_current_type wheel_current;





  typedef boost::shared_ptr< ::sentry_chassis_controller::WheelState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentry_chassis_controller::WheelState_<ContainerAllocator> const> ConstPtr;

}; // struct WheelState_

typedef ::sentry_chassis_controller::WheelState_<std::allocator<void> > WheelState;

typedef boost::shared_ptr< ::sentry_chassis_controller::WheelState > WheelStatePtr;
typedef boost::shared_ptr< ::sentry_chassis_controller::WheelState const> WheelStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentry_chassis_controller::WheelState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentry_chassis_controller::WheelState_<ContainerAllocator1> & lhs, const ::sentry_chassis_controller::WheelState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steering_angle == rhs.steering_angle &&
    lhs.wheel_speed == rhs.wheel_speed &&
    lhs.wheel_velocity == rhs.wheel_velocity &&
    lhs.wheel_torque == rhs.wheel_torque &&
    lhs.wheel_current == rhs.wheel_current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentry_chassis_controller::WheelState_<ContainerAllocator1> & lhs, const ::sentry_chassis_controller::WheelState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentry_chassis_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentry_chassis_controller::WheelState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentry_chassis_controller::WheelState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_chassis_controller::WheelState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1968715a3f1131762c929bdab65e2993";
  }

  static const char* value(const ::sentry_chassis_controller::WheelState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1968715a3f113176ULL;
  static const uint64_t static_value2 = 0x2c929bdab65e2993ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentry_chassis_controller/WheelState";
  }

  static const char* value(const ::sentry_chassis_controller::WheelState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"std_msgs/Header header\n"
"float64[4] steering_angle   # 四个轮子的转向角度（弧度）\n"
"float64[4] wheel_speed      # 四个轮子的转速(rad/s)\n"
"float64[4] wheel_velocity   # 四个轮子的线速度(m/s)\n"
"float64[4] wheel_torque     # 四个轮子的输出扭矩(Nm)\n"
"float64[4] wheel_current    # 四个轮子的电流(A)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sentry_chassis_controller::WheelState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering_angle);
      stream.next(m.wheel_speed);
      stream.next(m.wheel_velocity);
      stream.next(m.wheel_torque);
      stream.next(m.wheel_current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentry_chassis_controller::WheelState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentry_chassis_controller::WheelState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_angle: ";
    if (v.steering_angle.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.steering_angle.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.steering_angle[i]);
    }
    if (v.steering_angle.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_speed: ";
    if (v.wheel_speed.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_speed.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.wheel_speed[i]);
    }
    if (v.wheel_speed.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_velocity: ";
    if (v.wheel_velocity.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_velocity.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.wheel_velocity[i]);
    }
    if (v.wheel_velocity.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_torque: ";
    if (v.wheel_torque.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_torque.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.wheel_torque[i]);
    }
    if (v.wheel_torque.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_current: ";
    if (v.wheel_current.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_current.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.wheel_current[i]);
    }
    if (v.wheel_current.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTRY_CHASSIS_CONTROLLER_MESSAGE_WHEELSTATE_H
