(cl:in-package rm_msgs-msg)
(cl:export '(OVERLAPPING_SUPPLY_STATION_STATE-VAL
          OVERLAPPING_SUPPLY_STATION_STATE
          NAN_OVERLAPPING_SUPPLY_STATION_STATE-VAL
          NAN_OVERLAPPING_SUPPLY_STATION_STATE
          SUPPLIER_ZONE_STATE-VAL
          SUPPLIER_ZONE_STATE
          SMALL_POWER_RUNE_STATE-VAL
          SMALL_POWER_RUNE_STATE
          LARGE_POWER_RUNE_STATE-VAL
          LARGE_POWER_RUNE_STATE
          CENTRAL_ELEVATED_GROUND_STATE-VAL
          CENTRAL_ELEVATED_GROUND_STATE
          TRAPEZOIDAL_ELEVATED_GROUND_STATE-VAL
          TRAPEZOIDAL_ELEVATED_GROUND_STATE
          BE_HIT_TIME-VAL
          BE_HIT_TIME
          BE_HIT_TARGET-VAL
          BE_HIT_TARGET
          CENTRAL_POINT_STATE-VAL
          CENTRAL_POINT_STATE
          OWN_FORTRESS_STATE-VAL
          OWN_FORTRESS_STATE
          STAMP-VAL
          STAMP
))