(cl:in-package rm_msgs-msg)
(cl:export '(CHASSIS_POWER-VAL
          CHASSIS_POWER
          CAP_ERROR_FLAG-VAL
          CAP_ERROR_FLAG
          CAP_RECEIVED_MSG-VAL
          CAP_RECEIVED_MSG
          CAPACITY_REMAIN_CHARGE-VAL
          CAPACITY_REMAIN_CHARGE
          CAPACITY_DISCHARGE_POWER-VAL
          CAPACITY_DISCHARGE_POWER
          STATE_MACHINE_RUNNING_STATE-VAL
          STATE_MACHINE_RUNNING_STATE
          POWER_MANAGEMENT_PROTECTION_INFO-VAL
          POWER_MANAGEMENT_PROTECTION_INFO
          POWER_MANAGEMENT_TOPOLOGY-VAL
          POWER_MANAGEMENT_TOPOLOGY
          STAMP-VAL
          STAMP
))