(cl:in-package rm_msgs-msg)
(cl:export '(BULLET_ALLOWANCE_NUM_17_MM-VAL
          BULLET_ALLOWANCE_NUM_17_MM
          BULLET_ALLOWANCE_NUM_42_MM-VAL
          BULLET_ALLOWANCE_NUM_42_MM
          COIN_REMAINING_NUM-VAL
          COIN_REMAINING_NUM
          PROJECTILE_ALLOWANCE_FORTRESS-VAL
          PROJECTILE_ALLOWANCE_FORTRESS
          STAMP-VAL
          STAMP
))